### ISSUE TITLE
通过企业号发送红包接口问题

### ISSUE THREAD

**Issue by wwlleo0730** [foxinmy/weixin4j#106]
我这边版本暂时是1.7.0，对比了下1.7.3，好像代码没有变化。

com.foxinmy.weixin4j.api.CashApi 中

sendRedpack(InputStream certificate,Redpacket redpacket) 方法

直接使用了企业号的id作为 wxappid。

但是我这边实际测试下来，需要指定发送红包的应用，是需要传递通过如下文档里描述的appid才行：

http://qydev.weixin.qq.com/wiki/index.php?title=Userid%E4%B8%8Eopenid%E4%BA%92%E6%8D%A2%E6%8E%A5%E5%8F%A3

**Comment by foxinmy** [comment]
感谢反馈。
wxappid 就是企业号的corpid。

> 需要指定发送红包的应用
这点是在哪有说明呢？我这边代码跟支付文档有一段时间没去同步对比更新了，可能会有所纰漏。

感谢使用。

**Comment by wwlleo0730** [comment]
http://qydev.weixin.qq.com/wiki/index.php?title=%E5%BE%AE%E4%BF%A1%E7%8E%B0%E9%87%91%E7%BA%A2%E5%8C%85/%E4%BC%81%E4%B8%9A%E4%BB%98%E6%AC%BE

> 企业号开通微信支付后，即可使用微信红包功能。
在使用微信红包前，请仔细阅读以下流程：
确定需要发放红包的企业号应用和成员名单；
使用企业号（userid转openid接口），将应用ID和成员userid转换成红包参数中要求的appid和openid；
注意：在使用userid转openid接口时，**请务必传参agentid来获取对应的appid，否则会导致红包发送失败**

我实际测试下来，wxappid里也是只能填指定应用转换后对应的appid，而不是企业号的corpid

如果填corpid，是返回错误码：

OPENID_ERROR	openid和appid不匹配        发红包的openid必须是本appid下的openid

**Comment by foxinmy** [comment]
明白了...这里有点坑，我修改下代码。（：

**Comment by foxinmy** [comment]
```java
/**
	 * 发放红包 企业向微信用户个人发现金红包
	 *
	 * @param redpacket
	 *            红包信息
	 * @param appId
	 *            应用ID 可为空 主要是针对企业号支付时传入的agentid
	 * @return 发放结果
	 * @see com.foxinmy.weixin4j.payment.mch.Redpacket
	 * @see com.foxinmy.weixin4j.payment.mch.RedpacketSendResult
	 * @see <a href=
	 *      "https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=13_5">
	 *      发放现金红包接口</a>
	 * @see <a href=
	 *      "https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=16_5">
	 *      发放裂变红包接口</a>
	 * @throws WeixinException
	 */
	public RedpacketSendResult sendRedpack(Redpacket redpacket, String appId)
			throws WeixinException {
```

重载了一个方法。

**Comment by wwlleo0730** [comment]
今天早上实际使用了这个功能，整个集团20000个红包，暂时没发现什么问题。

**Comment by foxinmy** [comment]
API有改动：

```java
public RedpacketSendResult sendRedpack(Redpacket redpacket)
			throws WeixinException {
```

企业号appid通过set进去：

```java
redpacket.setAppid(appid);
```
