### ISSUE TITLE
使用spring-boot打成jar包发布，会出问题

### ISSUE THREAD

**Issue by FlatMan89** [foxinmy/weixin4j#115]
### 使用 idea+springboot+weixin4j-mp 进行开发
- 在idea中进行开发调试的时候没有问题
- 打包成`jar`包进行发布，一旦对`WeixinProxy`进行`new`操作，会报出找不到`Weixin4jConfigUtil`这个类异常
- 初步怀疑是在spring-boot环境中打成jar包的话，`Weixin4jConfigUtil`读取`weixin.properties`时出现问题，导致初始化`Weixin4jConfigUtil`失败，造成找不到`Weixin4jConfigUtil`这个类的异常
- 不知道是不是这个原因，望回复。

**Comment by foxinmy** [comment]
不好意思。

spring-boot没试过，
不过应该可以用new WeixinProxy(new WeixinAccount(id,secret)) 这样的构造去解决。

感谢反馈。

**Comment by FlatMan89** [comment]
@foxinmy 感觉回答，我去试试。

**Comment by FlatMan89** [comment]
@foxinmy 用你的方法解决了这个问题，再次感谢！！
