### ISSUE TITLE
建议提供刷新AccessToken的机制

### ISSUE THREAD

**Issue by macthink** [foxinmy/weixin4j#12]
有时候因为各种其他的原因，可能让AccessToken提前失效，调用接口会出现40001错误，故建议提供手动刷新AccessToken的机制。

**Comment by foxinmy** [comment]
你的提议不错 我将在1.6.2(暂时还为deploy到中央库)版本中加入

具体代码调用为：WeixinProxy.getTokenHolder.refreshToken();

另外关于 #11 我这暂时没办法重现 你可以考虑升级版本到 1.6.0以上后再观察

中秋愉快 ( :

**Comment by macthink** [comment]
按照官方文档里的说法，AccessToken应该会有2个小时的生命周期。按照这几天的运行情况来看，其实大部分情况下，都撑不到2个小时，这个是什么原因，你之前遇到过吗？

**Comment by foxinmy** [comment]
暂时没有遇到过（我的环境中用的是Redis来缓存token

首先要确定你的token存储策略 weixin4j默认是用文件的形式来保存的

这样会有两个潜在问题

1 如果在其他地方(不是同一台机器)也调用了获取token接口 那么之前的token即使没过期也会用不了

2 不排除其他进程修改了那个存放token的xml文件

当然如果环境中支持redis(或memcached) 强烈建议使用:https://github.com/foxinmy/weixin4j/wiki/%E7%94%A8redis%E4%BF%9D%E5%AD%98token

你可以自己实现 TokenStorager

**Comment by macthink** [comment]
好的。

**Comment by foxinmy** [comment]
突然想起个事 关于token的
在微信公众平台里面 token 应该是有两种的

1 是通过 oauth授权得到的token 这个我暂时没有缓存起来

2 是主动调用接口获取到的token 也是大部分接口所需要的token 这个做了缓存处理

不知道对你有没有帮助。

另外1.6.2已release到central,明日应该可以直接依赖了。

  <dependency>
    <groupId>com.foxinmy</groupId>
    <artifactId>weixin4j-mp</artifactId>
    <version>1.6.2</version>
  </dependency>

**Comment by macthink** [comment]
这个暂时没找到原因，找个时间再研究。
