### ISSUE TITLE
刚刚申请微信支付， 没有财付通的partnerKey

### ISSUE THREAD

**Issue by scofier** [foxinmy/weixin4j#121]
只收到一封邮件，没有《财付通提醒您：您的财付通商户申请资料已经通过》这封邮件

请问怎么设置partnerKey？ 或者partnerKey去哪里找？

`WEIXIN_OLD_PAY_ACCOUNT = new WeixinOldPayAccount("请填入v2版本的appid",
				"请填入v2版本的appSecret", "请填入v2版本的paysignkey", "请填入v2版本的partnerId",
				"请填入v2版本的partnerKey");`

**Comment by foxinmy** [comment]
财付通的partnerKe是老版本的支付，现在都不需要了。
