### ISSUE TITLE
Error:(12, 16) java: 无法访问com.foxinmy.weixin4j.model.WeixinAccount   找不到com.foxinmy.weixin4j.model.WeixinAccount的类文件

### ISSUE THREAD

**Issue by wangfengcool** [foxinmy/weixin4j#122]
Error:(12, 16) java: 无法访问com.foxinmy.weixin4j.model.WeixinAccount
  找不到com.foxinmy.weixin4j.model.WeixinAccount的类文件

**Comment by foxinmy** [comment]
能否提供更多的详细信息呢？

比如是在什么场景下触发，开发环境等等。
