### ISSUE TITLE
调用退款接口为什么出现Fatal Error？

### ISSUE THREAD

**Issue by jmbkeyes** [foxinmy/weixin4j#124]
[Fatal Error] :1722:33: 元素内容必须由格式正确的字符数据或标记组成。

调试过程中看到返回的数据如下
<xml><return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<appid><![CDATA[wxc730104d220c5172a9]]></appid>
<mch_id><![CDATA[13126811601]]></mch_id>
<nonce_str><![CDATA[NDTUKuLHyg6frgcB]]></nonce_str>
<sign><![CDATA[7112EC7CDBD2773AFD56D7021222CE89]]></sign>
<result_code><![CDATA[FAIL]]></result_code>
<err_code><![CDATA[ORDERNOTEXIST]]></err_code>
<err_code_des><![CDATA[订单不存在]]></err_code_des>
</xml>，
调用WeixinErrorUtil.getText(code)里的xmlReader.parse(new InputSource(new ByteArrayInputStream(errorXmlByteArray)));之后出现log，同时抛SAXException

**Comment by foxinmy** [comment]
嗯...感谢反馈。

这里是因为在error.xml里写了一些非法字符(比如<、>这些)，造成获取微信错误信息时解析xml出错。

但前提是调用接口已经出错了才会触发SAXException异常，所以还是要先看看接口抛出的异常。
