### ISSUE TITLE
有没有一个简单的文档？

### ISSUE THREAD

**Issue by cocca883** [foxinmy/weixin4j#13]
quick start   才拿到想快速入手，不知道从哪里入手 呢

**Comment by foxinmy** [comment]
微信公众平台开发：https://github.com/foxinmy/weixin4j/blob/master/weixin4j-mp/README.md
微信企业号开发：https://github.com/foxinmy/weixin4j/blob/master/weixin4j-qy/README.md
微信消息服务器开发：https://github.com/foxinmy/weixin4j/blob/master/weixin4j-server/README.md

如不明白可继续comment...

**Comment by looly** [comment]
靠注释 + 微信官方文档，很简单。作者注释非常详细~

**Comment by wulinjie122** [comment]
哪里详细？看了半天还是不知道怎么用。

**Comment by looly** [comment]
核心是WeixinProxy，里面作者封装了相应的方法，方法和参数与官方文档相同。

**Comment by cocca883** [comment]
WeiXin4JUtils.getWeixinProxy().downloadMedia(mediaId, false);
此方法下载媒体图片，为什么下载下来的Content-Type是text/plain? Content-disposition也是空，以至于MediaDownloadResult中获取到的文件名是XXXXXX.plain，应该是jpg或者jpeg格式的图片

**Comment by cocca883** [comment]
我自己大概是这样写的，就可以正常获取：
CloseableHttpClient httpClient = HttpClients.custom().setSSLSocketFactory(createSSLConnSocketFactory()).setConnectionManager(connMgr).setDefaultRequestConfig(requestConfig).build();
    	HttpGet httpget = new HttpGet(URL);  
        CloseableHttpResponse response = null;
        ContentBody reponseContentBody = null;
        
        try {
        	httpget.setConfig(requestConfig);
            response = httpClient.execute(httpget);  
            int statusCode = response.getStatusLine().getStatusCode();
            if (statusCode != HttpStatus.SC_OK) {
                return null;
            }
            String fileNameHeader = response.getHeaders("Content-disposition")[0].getValue();
//能正常获取到Content-disposition值，里面含有filename
} catch (Exception e) {
            e.printStackTrace();
        }

**Comment by foxinmy** [comment]
用的啥版本？

**Comment by zhoujinliang** [comment]
你这么写文档不是不行，但是组织不太好，看了你写的代码，还不错，建议在wiki中完善文档。

**Comment by foxinmy** [comment]
@zhoujinliang 嗯 有时间我会补充的。

**Comment by zhoujinliang** [comment]
之前我用的一个库：https://github.com/chanjarster/weixin-java-tools/wiki
我觉得他文档写的还不错。
文档如果从用户角度，在使用流程上考虑就完美了。

**Comment by rememberber** [comment]
项目非常不错，严重支持！！希望增加环境搭建相关的使用说明，最好有一个从搭建到使用的简单的demo

**Comment by foxinmy** [comment]
文档已在陆陆续续编写中：
https://github.com/foxinmy/weixin4j/wiki
