### ISSUE TITLE
使用memcached缓存token时空指针异常

### ISSUE THREAD

**Issue by HisaYing** [foxinmy/weixin4j#133]
init以后
![default](https://user-images.githubusercontent.com/37523008/37574631-3485f27c-2b5d-11e8-94b2-f041cac7ddea.png)此时Memcache中有weixin4j_cache_keys，此后若Memcache宕掉，此时
![default](https://user-images.githubusercontent.com/37523008/37574654-67723d12-2b5d-11e8-9434-e96ced44050c.png)
必有空指针异常。

**Comment by foxinmy** [comment]
感谢反馈，我加个判断吧。或者你有更好的建议也可以一块讨论。：）
