### ISSUE TITLE
此方法下载媒体图片，为什么下载下来的Content-Type是text/plain?

### ISSUE THREAD

**Issue by cocca883** [foxinmy/weixin4j#15]
WeiXin4JUtils.getWeixinProxy().downloadMedia(mediaId, false);
此方法下载媒体图片，为什么下载下来的Content-Type是text/plain? Content-disposition也是空，以至于MediaDownloadResult中获取到的文件名是XXXXXX.plain，应该是jpg或者jpeg格式的图片

我自己大概是这样写的，就可以正常获取：
CloseableHttpClient httpClient = HttpClients.custom().setSSLSocketFactory(createSSLConnSocketFactory()).setConnectionManager(connMgr).setDefaultRequestConfig(requestConfig).build();
HttpGet httpget = new HttpGet(URL);

CloseableHttpResponse response = null;
ContentBody reponseContentBody = null;
    try {
        httpget.setConfig(requestConfig);
        response = httpClient.execute(httpget);  
        int statusCode = response.getStatusLine().getStatusCode();
        if (statusCode != HttpStatus.SC_OK) {
            return null;
        }
        String fileNameHeader = response.getHeaders("Content-disposition")[0].getValue();
       //能正常获取到Content-disposition值，里面含有filename
} catch (Exception e) {
e.prin

**Comment by foxinmy** [comment]
感谢反馈

请问weixin4j用的是啥版本

**Comment by cocca883** [comment]
前几天下载的原代码，我是直接下载的github上的原代码的，因为我发现http://mvnrepository.com/search?q=weixin4j 上的1.6.3包maven下来与原代码不一至。

**Comment by cocca883** [comment]
昨天晚上是text/plain，今天早上来了试，前几次就是对的：text/jpeg，但几次之后，又一直是text/plain了

**Comment by foxinmy** [comment]
我增加了 从ContentDispositionHeader 提取 filename的代码 你拉取代码 再试试

content-type 微信返回的是什么 我这没做任何处理啊。

要不 你提供下 media_id 和 能用的  access_token  我这边调一下。

**Comment by cocca883** [comment]
做其它模块去了，能加一下我QQ吗：171339，我发media_id 和 能用的 access_token给你。我发现，我那样的写法还是会出现text/plain，只是出现的机率较少

**Comment by foxinmy** [comment]
我先关了，有问题再open。（：
