### ISSUE TITLE
微信支付官方sdk的xml漏洞是否影响weixin4j

### ISSUE THREAD

**Issue by kiwiflydream** [foxinmy/weixin4j#157]
https://xz.aliyun.com/t/2426

> 微信支付商户，如果你在使用支付业务回调通知中，存在以下场景，有使用XML解析的情况，请务必检查是否对XML的XXE漏洞进行了防范。

1、支付成功通知；
2、退款成功通知；
3、委托代扣签约、解约、扣款通知；
4、车主解约通知；

【检查及修复建议】：

【PHP】
libxml_disable_entity_loader(true);

【JAVA】
DocumentBuilderFactory dbf =DocumentBuilderFactory.newInstance();
dbf.setExpandEntityReferences(false);

【.Net】
XmlResolver = null;

【Python】
from lxml import etree
xmlData = etree.parse(xmlSource,etree.XMLParser(resolve_entities=False))

【c/c++(常用库为libxml2 libxerces-c)】

【libxml2】:  
确保关闭配置选项：XML_PARSE_NOENT 和 XML_PARSE_DTDLOAD
2.9版本以上已修复xxe

【libxerces-c】：
如果用的是XercesDOMParser:
XercesDOMParser *parser = new XercesDOMParser;
parser->setCreateEntityReferenceNodes(false);

如果是用SAXParser:
SAXParser* parser = new SAXParser;
parser->setDisableDefaultEntityResolution(true);

如果是用SAX2XMLReader:
SAX2XMLReader* reader = XMLReaderFactory::createXMLReader();
parser->setFeature(XMLUni::fgXercesDisableDefaultEntityResolution, true);

更多开源库/语言版本的修复建议可参考：
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#C.2FC.2B.2B

**Comment by foxinmy** [comment]
感谢反馈，已修复，请更新版本号为1.8.2
