### ISSUE TITLE
为啥payUtils都要写成静态的？

### ISSUE THREAD

**Issue by zhoujinliang** [foxinmy/weixin4j#16]
如题

**Comment by foxinmy** [comment]
出于两点考虑。

一、完全是为了方便 直接调用接口。

二、PayUtils里面的接口都是跟微信支付相关 包括 「支付签名」、「创建h5 jsAPI 支付串」、「创建获取微信地址字符串」、「统一下单接口」、「构建natvie 原生支付链接」、「提交扫码支付」这些接口其实都不需要传递 access_token 所以我干脆就独立出来了。

不过 你提的问题也有道理 我以后会考虑放到 WeixinPayProxy 里面去的
