### ISSUE TITLE
 企业微信下缺少 TextCard 通知格式

### ISSUE THREAD

**Issue by caoyiheng** [foxinmy/weixin4j#165]
企业微信下缺少 TextCard 通知格式。
{
   "touser" : "UserID1|UserID2|UserID3",
   "toparty" : "PartyID1 | PartyID2",
   "totag" : "TagID1 | TagID2",
   "msgtype" : "textcard",
   "agentid" : 1,
   "textcard" : {
            "title" : "领奖通知",
            "description" : "<div class=\"gray\">2016年9月26日</div> <div class=\"normal\">恭喜你抽中iPhone 7一台，领奖码：xxxx</div><div class=\"highlight\">请于2016年10月10日前联系行政同事领取</div>",
            "url" : "URL",
            "btntxt":"更多"
   }
}

**Comment by MicroLord** [comment]
1.7.8版本确实没有，但1.9.0版本是有的，源码里面已经写了
