### ISSUE TITLE
卡券之会员卡接口缺失

### ISSUE THREAD

**Issue by eonezhang** [foxinmy/weixin4j#170]
相关文档请参见 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025283
不知道相关的API接口是否可以完善，我看到代码里面已经定义了相关的模型类，但是缺少接口定义与实现。com.foxinmy.weixin4j.model.card.MemberCard

**Comment by kit-lee** [comment]
有实现的，详细看，com.foxinmy.weixin4j.mp.api.CardApi
