### ISSUE TITLE
微信支付notify解析api

### ISSUE THREAD

**Issue by jimlaren** [foxinmy/weixin4j#2]
没有找到微信支付notify解析api，就是解析post回来的xml的，有没有例子可以看一下，谢谢。

**Comment by foxinmy** [comment]
在 支付示例 com.foxinmy.weixin4j.mp.action.PayAction 中有相关代码
jsNotifyV2 方法接收 v2支付时的回调
jsNotifyV3 方法接收 v3支付时的回调

**Comment by jimlaren** [comment]
好的，谢谢，我研究下。
