### ISSUE TITLE
lsof -p xxx 出现很多FIFO、pipe 的问题原因

### ISSUE THREAD

**Issue by laotu5i0** [foxinmy/weixin4j#24]
您好！1.6.6 有没有解决下面这个问题呢？
相似帖子：http://blog.csdn.net/zhang168/article/details/27567053

java    62953 root *310w  FIFO                0,8      0t0  9630083 pipe
java    62953 root *311u   REG                0,9        0     4158 [eventpoll]
java    62953 root *312r  FIFO                0,8      0t0  9630084 pipe
java    62953 root *313w  FIFO                0,8      0t0  9630084 pipe
java    62953 root *314u   REG                0,9        0     4158 [eventpoll]
java    62953 root *315r  FIFO                0,8      0t0  9630085 pipe
java    62953 root *316w  FIFO                0,8      0t0  9630085 pipe
java    62953 root *317u   REG                0,9        0     4158 [eventpoll]
java    62953 root *318r  FIFO                0,8      0t0  9630086 pipe
java    62953 root *319w  FIFO                0,8      0t0  9630086 pipe
java    62953 root *320u   REG                0,9        0     4158 [eventpoll]
java    62953 root *321r  FIFO                0,8      0t0  9630087 pipe
java    62953 root *322w  FIFO                0,8      0t0  9630087 pipe
java    62953 root *323u   REG                0,9        0     4158 [eventpoll]
java    62953 root *324r  FIFO                0,8      0t0  9630088 pipe
java    62953 root *325w  FIFO                0,8      0t0  9630088 pipe
java    62953 root *326u   REG                0,9        0     4158 [eventpoll]
java    62953 root *327r  FIFO                0,8      0t0  9630089 pipe
java    62953 root *328w  FIFO                0,8      0t0  9630089 pipe
java    62953 root *329u   REG                0,9        0     4158 [eventpoll]
java    62953 root *330r  FIFO                0,8      0t0  9630090 pipe
java    62953 root *331w  FIFO                0,8      0t0  9630090 pipe
java    62953 root *332u   REG                0,9        0     4158 [eventpoll]
java    62953 root *333r  FIFO                0,8      0t0  9630091 pipe
java    62953 root *334w  FIFO                0,8      0t0  9630091 pipe
java    62953 root *335u   REG                0,9        0     4158 [eventpoll]
java    62953 root *336r  FIFO                0,8      0t0  9630092 pipe
java    62953 root *337w  FIFO                0,8      0t0  9630092 pipe
java    62953 root *338u   REG                0,9        0     4158 [eventpoll]
java    62953 root *339r  FIFO                0,8      0t0  9630093 pipe
java    62953 root *340w  FIFO                0,8      0t0  9630093 pipe
java    62953 root *341u   REG                0,9        0     4158 [eventpoll]
java    62953 root *342r  FIFO                0,8      0t0  9630094 pipe
java    62953 root *343w  FIFO                0,8      0t0  9630094 pipe
java    62953 root *344u   REG                0,9        0     4158 [eventpoll]
java    62953 root *345r  FIFO                0,8      0t0  9630095 pipe
java    62953 root *346w  FIFO                0,8      0t0  9630095 pipe
java    62953 root *347u   REG                0,9        0     4158 [eventpoll]
java    62953 root *348r  FIFO                0,8      0t0  9630096 pipe
java    62953 root *349w  FIFO                0,8      0t0  9630096 pipe
java    62953 root *350u   REG                0,9        0     4158 [eventpoll]
java    62953 root *351r  FIFO                0,8      0t0  9630097 pipe
java    62953 root *352w  FIFO                0,8      0t0  9630097 pipe
java    62953 root *353u   REG                0,9        0     4158 [eventpoll]
java    62953 root *354r  FIFO                0,8      0t0  9630098 pipe
java    62953 root *355w  FIFO                0,8      0t0  9630098 pipe
java    62953 root *356u   REG                0,9        0     4158 [eventpoll]
[root@caimei365web10 ~]# lsof -p 62953 | grep pipe | wc -l
14848
[root@caimei365web10 ~]# lsof -p 62953 | grep eventpoll | wc -l
7424

**Comment by foxinmy** [comment]
很抱歉。。1.6.6的代码暂时没解决此问题。
最新代码是没有此问题的。。请等待下一个版本吧。
如果急的话请直接下载源码 自己install吧？

**Comment by laotu5i0** [comment]
OK，谢谢您的及时回复。
