### ISSUE TITLE
微信media api upload 上传媒体 类型文件，中文名称乱码，使用httpclient4

### ISSUE THREAD

**Issue by fengyapeng** [foxinmy/weixin4j#25]
微信media api upload 上传媒体 类型文件，使用httpclient4，经测试产生乱码。

**Comment by fengyapeng** [comment]
稍后补充test 代码。

**Comment by fengyapeng** [comment]
好吧。手头上没有test code，先贴上我的解决方案，com.foxinmy.weixin4j.http.weixin.WeixinRequestExecutor line num :83,
HttpMultipartMode.STRICT ->HttpMultipartMode.BROWSER_COMPATIBLE.
原因是因为： HttpMultipartMode.STRICT 在输出byte 的时候没有设置编码，BROWSER_COMPATIBLE 这是有编码。详见 你的code：
com.foxinmy.weixin4j.http.apache.HttpMultipart

case STRICT:
				for (NameValue field : header) {
					writeField(field, out);
				}
				break;
			case BROWSER_COMPATIBLE:
				// Only write Content-Disposition
				// Use content charset
				NameValue cd = part.getHeader().getField(
						MIME.CONTENT_DISPOSITION);
				writeField(cd, this.charset, out);
				String filename = part.getBody().getFilename();
				if (filename != null) {
					NameValue ct = part.getHeader().getField(MIME.CONTENT_TYPE);
					writeField(ct, this.charset, out);
				}
				break;

**Comment by foxinmy** [comment]
能给个case么  是上传什么类型的素材？

**Comment by fengyapeng** [comment]
@Before
	public void init() {
		mediaApi = new MediaApi(tokenHolder);
	}

@Test
	public void uploadFile() throws IOException, WeixinException {
		File file = new File("C:\\Users\\fengyapeng\\Desktop\\新建文本文档.txt");
		MediaUploadResult mediaResult = mediaApi.uploadMedia(0, new FileInputStream(
				file), "新建文本文档.txt");
		Assert.assertNotNull(mediaResult.getMediaId());
		System.out.println(mediaResult);
	}
引入 httpclient4.日志级别：debug。你会看到http client 的日志 ，其中filename 乱码了。

**Comment by foxinmy** [comment]
哥们 我这上传的filename是正常的 下载确实乱码了。。遇到过么。。

**Comment by fengyapeng** [comment]
下载的乱码无能为力。因为：微信 response header 根本没有告诉我们到底是要content-type 的编码，所以默认使用iso-8859-1 的形式编码。需要自行处理。

**Comment by foxinmy** [comment]
在weixin4j里面我实现了 四种Httpclient

SimpleHttpClient: 下载文件时 文件名会乱码

HttpComponent3：设置了HttpElementCharset为utf8无乱码

HttpComponent4：同HttpComponent3

Netty4HttpClient：暂时没想到办法解决
