### ISSUE TITLE
有没有webdemo  不知道如何下手

### ISSUE THREAD

**Issue by ygp1026** [foxinmy/weixin4j#27]
新手开发微信应用，感觉咱们的功能很强大，但是无从下手。
能不能有基于servlet或者springmvc的例子。

邮箱ygp1026@126.com如果有相关文档发一份，不胜感激

**Comment by foxinmy** [comment]
感谢关注。

weixin4j本身没有针对 servlet或springmvc 的支持代码。

在微信开发里面大概有两种连接方式。

一：主动连接
也就是我们主动调用微信的接口，比如获取用户信息、发送客服消息等这类的接口。
这里的实现可以看看(weixin4j-mp服务号、订阅号开发)[https://github.com/foxinmy/weixin4j/tree/master/weixin4j-mp]以及(weixin4j-qy企业号开发)[https://github.com/foxinmy/weixin4j/tree/master/weixin4j-qy]

二：被动连接
微信服务器会把用户在公众号里面发送的任何消息(比如发送语音、文本等)以及其它系统消息(群发结果通知等)推送到我们在开发者模式填写的服务器URL上去，这种方式可以看作是被动调用。
这里的实现为(weixin4j-server)[https://github.com/foxinmy/weixin4j/tree/master/weixin4j-server]


所以其实weixin4j分了两个维度去分别做了实现。

如果你只是单独得做接口调用，这里并不限于是web项目还是控制台项目，引入weixin4j-mp或weixin4j-qy包就行了。

如果你还想对用户的消息进行处理，可能就需要用到weixin4j-server了，值得注意的是在spring项目需要单独开启一个线程去启动server。

demo我发你邮箱了，请注意查收。

**Comment by foxinmy** [comment]
[weixin4j-web.zip](https://github.com/foxinmy/weixin4j/files/93784/weixin4j-web.zip)

**Comment by ygp1026** [comment]
十分感谢楼主。
解释的十分清晰，已经学会开发被动模式，主动模式经过楼主的代码很方便实现。
楼主又给了webdemo，十分感谢。
我这几天会继续尝试，会多关注，把这个插件推广开。

**Comment by ygp1026** [comment]
再次请教一下：
楼主给的demo中主动例子运行OK，但是被动例子好像没有启动成功。
如果我自己写一个供微信调用的方法，可能就无法调动到楼主的其他方法。
-----------------------------------------------------
1、我看楼主的初始化启动，

**Comment by wenzhongyi** [comment]
作者你好：
             maven 源码 中文是乱码~~~

**Comment by foxinmy** [comment]
@wenzhongyi 源代码的编码方式是 UTF-8 你那边是多少？

**Comment by wenzhongyi** [comment]
是的。

**Comment by wenzhongyi** [comment]
你用maven 下载jar包这样打开源码试试。。先把你本机的关掉。

**Comment by wenzhongyi** [comment]
直接从maven仓库下载。

**Comment by foxinmy** [comment]
哥们。。我这好好的 没有乱码

**Comment by wenzhongyi** [comment]
确实有问题。可能你打开的方式不对。

**Comment by foxinmy** [comment]
@wenzhongyi 有没有图呀 上个图。。我这重现不了。。而且之前用过的朋友也未提及此问题呀

**Comment by wenzhongyi** [comment]
qq8831694

**Comment by wenzhongyi** [comment]
![default](https://cloud.githubusercontent.com/assets/6345654/12476771/72fcd6b0-c066-11e5-88f6-979704c89278.png)

**Comment by lqxion** [comment]
最近发现比较多的同学均在学习使用您的框架 希望能建个群供大家讨论哈哈 不是可行不

**Comment by wenzhongyi** [comment]
点击链接加入讨论组"微支付H5":
http://url.cn/28d7Jh2
该链接将于16-10-7 15:47失效
