### ISSUE TITLE
关于token文件缓存的问题

### ISSUE THREAD

**Issue by ywj070101526** [foxinmy/weixin4j#28]
配置weixin4j.properties   token的路径后，例如：/tmp/token, 第一次接入微信后，会在token文件夹下产生一个token文件，之后，如果我把tmp或者token文件夹删掉后，会报“系统找不到指定的路径”，我直接把产生的token文件删掉，不会报这个错，会重新生成一个token缓存文件

**Comment by foxinmy** [comment]
这里面是这样的

1 weixin4j支持不同方式的token存储[TokenStorager](https://github.com/foxinmy/weixin4j/blob/master/weixin4j-base/src/main/java/com/foxinmy/weixin4j/token/TokenHolder.java)

2 weixin4j默认的token存储方式为本地文件存储[FileTokenStorager](https://github.com/foxinmy/weixin4j/tree/master/weixin4j-base/src/main/java/com/foxinmy/weixin4j/token)

3 weixin4j在实例化WeixinProxy类时会加载一次配置文件(weixin4j.properties),这个时候会判断配置文件中的key如果以.path结尾的话就会尝试创建目录。

4 你上面的问题可以考虑 在删除文件夹后可以重启程序或者配置另外的目录

感谢使用。
