### ISSUE TITLE
生成native支付时，如何生成product，没有找到api

### ISSUE THREAD

**Issue by jimlaren** [foxinmy/weixin4j#3]
生成native支付时，如何生成product，没有找到api，里边的参数productId，是不是需要把订单包装成商品，有没有api可以生成，生成后，可不可以删除。

**Comment by foxinmy** [comment]
没有单独针对native支付的API 不过在一个工具类(PayUtil)中有实现
对于 productId 

在v2支付中 productId 其实就是 你的商品或者订单id 无需调用其它接口生成
直接调用：
```java 
String com.foxinmy.weixin4j.mp.payment.PayUtil.createNativePayRequestURLV2(WeixinMpAccount weixinAccount, String productId)
```
发起支付时微信服务器会向你当初申请支付接口时填写的package回调地址 这个时候你的服务器需要返回订单信息，示例请看：
```java
String com.foxinmy.weixin4j.mp.action.PayAction.nativeNotifyV2(InputStream inputStream)
```

在v3支付中 又分两种情况 
a 静态链接模式
其实就相当于v2的支付，不过在v3中需要调用「统一支付接口」生成prepayid返回给微信
prepayid的生成请看:
```java
PrePay com.foxinmy.weixin4j.mp.payment.PayUtil.createPrePay(PayPackageV3 payPackage, String paySignKey) throws PayException
```

b 预生成订单模式
这个模式下需要刚开始就调用统一支付接口(`com.foxinmy.weixin4j.mp.payment.PayUtil.createPrePay`)，
结果中会返回 code_url,直接使用该参数值作为native 的支付链接或者生成二维码即可
在weixin4j中具体做法是规定PayPackageV3中的TradeType为NATIVE
然后获取prepay对象中的codeUrl

对于需要回调拿package的native来说 product_id删不删除没什么关系 因为它就是订单ID 应该可以重复生成支付链接

对于预生成的订单来说 我看了下文档没有特别说明不能重复生成code_url 不过这种模式生成一次之后下面就不用再生成了吧 比较适用于不用一步一步选购的支付场景

希望能帮到你～

**Comment by jimlaren** [comment]
我是想在网页版做微信支付的二维码，用户手机扫描就可以支付了，如果预生成订单模式可以的话，我测试下，有问题再来咨询，谢谢了。

**Comment by jimlaren** [comment]
PayPackageV3 payPackageV3 = new PayPackageV3(weixinMpAccount, "",
				"订单:" + order.getNumber(), order.getNumber(),
				Double.parseDouble("" + order.getPayPrice()), ip,
				TradeType.NATIVE);
		payPackageV3.setProduct_id(order.getNumber());
		payPackageV3.setNotify_url(WeixinConstants.PAY_NOTIFY_URL);
		PrePay prePay = null;
		try {
			prePay = PayUtil.createPrePay(payPackageV3,
					WeixinConstants.PAY_SIGN_KEY);
		} catch (PayException e) {
			e.printStackTrace();
		}
		if (prePay != null) {
			return prePay.getCodeUrl();
		}
		return null;

提示如下错误：
com.foxinmy.weixin4j.exception.PayException: FAIL,签名错误

**Comment by foxinmy** [comment]
你好 问题可能是某个字段的命名不正确导致签名串出错 
我把package中的字段名重新调整了下 请拉取最新代码
本地native支付测试通过 相关代码
```java

	@Test
	public void nativeV3() throws WeixinException {
		PayPackageV3 payPackageV3 = new PayPackageV3(ACCOUNT3,
				"oyFLst1bqtuTcxK-ojF8hOGtLQao", "native测试", "T0001", 0.1d,
				"127.0.0.1", TradeType.NATIVE);
		payPackageV3.setProductId("0001");
		payPackageV3.setNotifyUrl("xxxx");
		PrePay prePay = null;
		try {
			prePay = PayUtil.createPrePay(payPackageV3,
					ACCOUNT3.getPaySignKey());
		} catch (PayException e) {
			e.printStackTrace();
		}
		System.err.println(prePay);
	}
```
返回：
```java
PrePay [tradeType=NATIVE, prepayId=wx2015012211130039dbf0ec310907934748, codeUrl=weixin://wxpay/bizpayurl?pr=xJxMZws, appId=wx0d1d598c0c03c999, mchId=10020674, subMchId=null, nonceStr=WOsi0QBjLh1Ua2ci, sign=63B121068B95B7886D0E35D4D7FA128A, deviceInfo=null, recall=null, returnCode=SUCCESS, returnMsg=OK, resultCode=SUCCESS, errCode=null, errCodeDes=null]

```

**Comment by jimlaren** [comment]
更新了，还是签名错误。
com.foxinmy.weixin4j.exception.PayException: FAIL,签名错误

**Comment by jimlaren** [comment]
我是在电脑网页上生成二维码扫描，没法取得用户的openid，所以那个字段为空，不知道跟这个有没有关系。

**Comment by foxinmy** [comment]
openid是必须传入de

用户标识
openid
否
String(128)
用户在商户 appid 下的唯一 标识,trade_type 为 JSAPI 时,此参数必传,获取方式 见表头说明。

**Comment by foxinmy** [comment]
传入null试试

```java
PayPackageV3 payPackageV3 = new PayPackageV3(weixinMpAccount, null,
"订单:" + order.getNumber(), order.getNumber(),
Double.parseDouble("" + order.getPayPrice()), ip,
TradeType.NATIVE);
```

**Comment by jimlaren** [comment]
log信息：
WeixinMpAccount [openId=null, paySignKey=1d380b4edf3733ca38cf591150ac57818, partnerId=12236298011, partnerKey=1d380b4e1df3733ca38cf591150ac5788, mchId=100219613, deviceInfo=null, version=3, id=wx26652fa7a915ccf9, secret=f18d892541241564bcbd7d1b7f18e604, token=, encodingAesKey=]
PayPackageV3 [appid=wx26652fa71a915ccf9, mchId=100219613, deviceInfo=null, nonceStr=xsxL1V1UhbDcYk3c9, sign=null, tradeType=NATIVE, openid=, productId=U15012100426099, PayPackage [body=订单:U15012100426099, attach=null, outTradeNo=U15012100426099, totalFee=100, spbillCreateIp=115.238.168.135, timeStart=null, timeExpire=null, goodsTag=null, notifyUrl=http://www.test.com/weixin/notify]]

**Comment by jimlaren** [comment]
传入null可以了，谢谢了。

**Comment by foxinmy** [comment]
哥们 paysignkey 跟 secret不要随便暴露哦 我帮你删除了。
