### ISSUE TITLE
关于Token维护的细节

### ISSUE THREAD

**Issue by LaughingVzr** [foxinmy/weixin4j#30]
我需不需要自己实现token的维护，还是当发现token过期时自动完成token的获取和缓存，我觉得这个点作者有必要特殊说明一下，因为毕竟token是请求的凭证。

**Comment by foxinmy** [comment]
token并不需要自己维护，weixin4j在过期时会自动去刷新，当然你也可以调用TokenHolder#refreshToken手动刷新。

感谢使用

**Comment by LaughingVzr** [comment]
谢谢作者回答～
