### ISSUE TITLE
服务包weixin4j-server能否提供servlet版本？

### ISSUE THREAD

**Issue by think-gem** [foxinmy/weixin4j#32]
服务包weixin4j-server能否提供servlet版本？

**Comment by foxinmy** [comment]
不太建议把netty跟servlet混在一起。

在netty里如果要引入servlet需要写一个桥接(bridge)这样的东西。

类似于：https://github.com/bigpuritz/netty-servlet-bridge

我会考虑实现的，请等待吧。

**Comment by think-gem** [comment]
谢谢开源这么好的api，我仿照你的nettyserver我又写了一份spring的。
