### ISSUE TITLE
com.foxinmy.weixin4j.qy.api.MediaApi   listMaterialMedia 方法疑问

### ISSUE THREAD

**Issue by wwlleo0730** [foxinmy/weixin4j#39]
该方法如果查询参数 MediaType 不为 news 则永远返回空。

代码如下：

WeixinResponse response = weixinExecutor.post(
				String.format(material_media_list_uri, token.getAccessToken()),
		obj.toJSONString());
		obj = response.getAsJson();
		MediaRecord mediaRecord = JSON.toJavaObject(obj, MediaRecord.class);
		if (mediaType == MediaType.news) {
			mediaRecord.setItems(JSON.parseArray(obj.getString("itemlist"),
					MediaItem.class));
		}

**Comment by foxinmy** [comment]
这是一个bug，感谢反馈，已修复。
