### ISSUE TITLE
有没有示例代码可以参考？

### ISSUE THREAD

**Issue by barrywey** [foxinmy/weixin4j#4]
RT
比如：基本的入门使用方法
比如：微信介入
比如：回复信息
等等

**Comment by foxinmy** [comment]
需要一点java编程知识

可以参考 *server项目 比如其中的 TextAction  就是当用户向微信发送文字消息时 程序便会输出 「Hello World」其它需求可以自行发挥，只要在对应的action中处理请求即可，目前的文档可能不是很详细，日后会逐步完善的！多谢关注！！
