### ISSUE TITLE
QRapi 中的QRParameter 创建临时二维码的的sceneId 的最大长度问题

### ISSUE THREAD

**Issue by fengyapeng** [foxinmy/weixin4j#41]
scene_id	场景值ID，临时二维码时为32位非0整型，该数值的最大值为：4294967295。这个值已经超出了 Integer 最大值。

**Comment by fengyapeng** [comment]
建议用Long 类型。scene_id 如果超过 4294967295 调用api 接口也是可以，不过扫描事件推送过来的Id 为4294967295。

**Comment by foxinmy** [comment]
感谢反馈

没理解到wiki上的说明 这里应该是无符号整型 你说得是对的

```javaQRParameter com.foxinmy.weixin4j.mp.model.QRParameter.createTemporary(int expireSeconds, long sceneValue)```

临时二维码接口改正为 long 类型
