### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by movingboat** [foxinmy/weixin4j#47]
你好：
    在github 关注您的 weixin4j工具， 最近刚开始接触这块 正在学习。
在使用最新版本的工具过程中 直接初始化Weixin4jSuiteSettings，默认读取配置文件并将其转换成WeixinQyAccount实体时候，报空指针错误。
后续发现可能是WeixinQyAccount这个实体的代码中的问题， 
将 /**
	 * 多个应用套件信息
	 */
	private List<WeixinAccount> suiteAccounts 换成 suites 就可以了 是否我有什么地方出问题了 ？ 新手学习 还望解答 ，多谢。

**Comment by foxinmy** [comment]
很抱歉。

这是一个没注意到的bug。

已经修复，请关注最新源码。

感谢使用。
