### ISSUE TITLE
关于  http 请求的 建议

### ISSUE THREAD

**Issue by fengyapeng** [foxinmy/weixin4j#48]
1、其中使用netty，还是httpclient，还是simple 的，现在默认是netty，httpclient，simple 的 查找顺序；希望可以通过配置型选择使用哪一种 httpclient。
2、关于 connect time out 的问题，在我们测试的时候发现，在网络差的情况下，上传语音 or 视频的时候，经常会出现timeout 的问题，当我希望自定义 timeout  阀值 的时候，发现其很难自定义，且没有配置可言。如果有配置的话，也希望 上传 下载类的接口可以定义的时间长些；其他的json 的接口 定义的时间短些。
希望能尽快有解决方案。马上上线。。。
best wish for you

**Comment by foxinmy** [comment]
感谢反馈。

1、httpclient逻辑是这样的没错，暂时不可以通过配置来指定，但是可以通过如下代码指定缺省的httpclient:
```java
HttpClientFactory.setDefaultFactory(new HttpComponent4Factory());
```

2、真是想什么来什么，这是个已知问题⊙﹏⊙。其实是有个配置的地方的，在Weixin4jSettings配置类里面有个HttpParams属性可以去指定connection time out的参数值：https://github.com/foxinmy/weixin4j/wiki/%E9%BB%98%E8%AE%A4HttpParams。
但是。。。这个httparams参数我还没去实现(没有传递给WeixinRequestExecutor)，第二个的话就是httpparams可能是全局的，所有接口的调用都是使用这个参数。
我也一直在想一种比较好的解决方案......

**Comment by fengyapeng** [comment]
没有十全十美的方案。非常感谢。。。。

**Comment by foxinmy** [comment]
HttpClientFactory实现更多地配置选项
