### ISSUE TITLE
如何把weixin4j-server集成进现有的tomcat的系统

### ISSUE THREAD

**Issue by zaghost** [foxinmy/weixin4j#49]
weixin4j-server是一个独立的系统，但是如果要和现有的tomcat的系统集成，消息的处理要调用tomcat系统的函数，要如何来做
谢谢~

**Comment by foxinmy** [comment]
嗯... 你说的应该是servlet api吧，暂时不支持，请参考：https://github.com/foxinmy/weixin4j/issues/32

**Comment by zaghost** [comment]
了解，
要是有library版的weixin4j-server就好了，像weixin4j-base和weixin4j-mp一样被servlet调用

**Comment by jiaowonange8** [comment]
封装的很好啊，期待weixin4j-server能在spring项目中直接调用
