### ISSUE TITLE
user_getid_uri不正确。

### ISSUE THREAD

**Issue by wangjingfei** [foxinmy/weixin4j#5]
QY部分weixin.properties中的user_getid_uri应该是：
user_getid_uri={api_base_url}/user/getuserinfo?access_token=%s&code=%s&agentid=%d。

1.2版本中的代码是：
user_getid_uri={api_base_url}/getuserinfo?access_token=%s&code=%s&agentid=%d

能不能麻烦修正一下？谢谢！

**Comment by foxinmy** [comment]
多谢指出 这个接口我确实没测试过！ 已修正 请拉取最新代码！

**Comment by wangjingfei** [comment]
非常感谢！这个代码一般会多长时间更新到maven repos中呢？

**Comment by foxinmy** [comment]
嗯 因为上个版本(1.2)是过年放假之前发布的 距离现在没有太多的接口的更新

所以可能要等一段时间才会release到 maven中央仓库去

我这里建议两种解决方案 

1 直接git clone 到本地 然后运行 mvn package -Prelease 命令 得到jar包

2 下载https://github.com/foxinmy/weixin4j/releases/tag/weixin4j-1.2这里的weixin4j-qy-full-1.2.tar包

无论那种你都需要重新依赖 所以要想办法把jar包放到仓库里去

如果你没有用到私服 那么就用 install 命令 安装到本地仓库然后依赖

如果用到私服 则可以在管理员面板中上传jar包私服然后依赖

你可以自己定义一个version 不要跟我已经发布的版本号一致就好了

以上希望能帮到你。

**Comment by wangjingfei** [comment]
谢谢你的建议，我去试试install命令。另外建议这种BUG的修改可以以小版本的形式发布，如1.2.1，这样的话没有接口的改变但是又可以让你的用户去选择用没有bug的版本。

**Comment by foxinmy** [comment]
嗯 你的建议非常好，下个版本我准备这么干

在 2015年3月9日 下午4:26，Wang Jingfei <notifications@github.com>写道：
