### ISSUE TITLE
查询退款接口，返回的数据不全

### ISSUE THREAD

**Issue by fatherican** [foxinmy/weixin4j#50]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_5

退款查询接口，会包含每一笔退款的详细信息，但是在RefundRecord 的refundList 字段中，保存的仅仅有
![image](https://cloud.githubusercontent.com/assets/4585687/14343358/062268a8-fcd3-11e5-9f52-4197f5a094f8.png)

out_refund_no_0 、out_refund_no_1 这些原始微信返回的字段信息缺失。

**Comment by fatherican** [comment]
问题找到了 ， ListsuffixResultDeserializer  类中133行，在解析xml的过程中，微信的xml 的NODE节点有可能是<![CDATA[ ]]> 包裹，所以在监听xml解析事件的时候，需要监听XMLStreamConstants.CDATA事件， 修改成` if (event == XMLStreamConstants.CHARACTERS || event == XMLStreamConstants.CDATA)  `问题得到解决。

**Comment by foxinmy** [comment]
感谢反馈。

确实有这个问题，我等会更新下代码吧

**Comment by fatherican** [comment]
楼主 ，我 发了一个 pullRequest，可以合入到master

**Comment by foxinmy** [comment]
谢谢 已合并。
