### ISSUE TITLE
通过openId 集合群发的bug

### ISSUE THREAD

**Issue by fengyapeng** [foxinmy/weixin4j#52]
public String[] massByOpenIds(MassTuple tuple, String... openIds)
			throws WeixinException {
		if (tuple instanceof MpNews) {
			MpNews _news = (MpNews) tuple;
			List<MpArticle> _articles = _news.getArticles();
			if (StringUtil.isBlank(_news.getMediaId())) {
				if (_articles.isEmpty()) {
					throw new WeixinException(
							"mass fail:mediaId or articles is required");
				}
				tuple = new MpNews(uploadArticle(_articles));
			}
		}

哈哈哈

**Comment by foxinmy** [comment]
没看出来...哪里有bug？（：

**Comment by fengyapeng** [comment]
`这是你现在的代码的逻辑；`
if (tuple instanceof MpNews) {
			MpNews _news = (MpNews) tuple;
			List<MpArticle> _articles = _news.getArticles();
			if (StringUtil.isBlank(_news.getMediaId())
					&& (_articles == null || _articles.isEmpty())) {
				throw new WeixinException(
						"mass fail:mediaId or articles is required");
			}
			tuple = new MpNews(uploadArticle(_articles));
		}`
通过 的代码：`
if (tuple instanceof MpNews) {
MpNews _news = (MpNews) tuple;
List _articles = _news.getArticles();
if (StringUtil.isBlank(_news.getMediaId())) {
if (_articles.isEmpty()) {
throw new WeixinException(
"mass fail:mediaId or articles is required");
}
tuple = new MpNews(uploadArticle(_articles));
}

}`

**Comment by foxinmy** [comment]
哦 群发有两个方法 有一个方法逻辑是正确的 另一个就是你现在提的 我已作修改发自网易邮箱大师
            在2016年04月08日 16:59，fengyapeng 写道:这是你现在的代码的逻辑；
if (tuple instanceof MpNews) {
            MpNews _news = (MpNews) tuple;
            List _articles = _news.getArticles();
            if (StringUtil.isBlank(_news.getMediaId())
                    && (_articles == null || _articles.isEmpty())) {
                throw new WeixinException(
                        "mass fail:mediaId or articles is required");
            }
            tuple = new MpNews(uploadArticle(_articles));
        }
通过 的代码：
if (tuple instanceof MpNews) {
MpNews _news = (MpNews) tuple;
List _articles = _news.getArticles();
if (StringUtil.isBlank(_news.getMediaId())) {
if (_articles.isEmpty()) {
throw new WeixinException(
"mass fail:mediaId or articles is required");
}
tuple = new MpNews(uploadArticle(_articles));
}

}`
