### ISSUE TITLE
GroupApi.getGroups()返回List<Group>中的group.count无值

### ISSUE THREAD

**Issue by jspxcms** [foxinmy/weixin4j#55]
应该是Group类的count属性没有setCount(int count)方法导致的。

是漏了吗，还是有意为之？其他一些类也看到一些属性只有get方法没有set方法，如MpArticle的content属性。

**Comment by foxinmy** [comment]
感谢反馈。

> GroupApi.getGroups()返回List<Group>中的group.count无值

这个确实是个bug，已经修复了请关注最新代码。

> 其他一些类也看到一些属性只有get方法没有set方法

我的想法是尽量减少「实体传输类」的set方法，因为它本身就是一个数据载体的作用，不存在修改的场景，所以我在构建实体的时候会使用[@JSONCreator](https://github.com/alibaba/fastjson/blob/master/src/test/java/com/alibaba/json/bvt/parser/JSONCreatorTest.java)注解去做，尽量避免setter污染。

感谢使用。
