### ISSUE TITLE
多媒体下载接口没捕捉微信错误返回

### ISSUE THREAD

**Issue by kit-lee** [foxinmy/weixin4j#56]
MediaApi类
方法：public MediaDownloadResult downloadMedia(String mediaId, boolean isMaterial)
提交已失效的mediaId，没抛WeixinException
返回Filename   mediaId.plain
内容为微信出错的JSON内容：
{"errcode":40007,"errmsg":"invalid media_id hint: [fnNMbA0216e298]"}

**Comment by foxinmy** [comment]
感谢反馈。

这是一个bug，已修复请关注最新代码。

感谢使用。
