### ISSUE TITLE
获取用户地理位置的接口是否有开发？

### ISSUE THREAD

**Issue by ygp1026** [foxinmy/weixin4j#57]
楼主，wx.getLocation这个接口有实现吗？
我看JSSDK中有描述，不过没找到相关实现和调用

**Comment by foxinmy** [comment]
嗯 JSSDK接口 有实现，用法如下。
第一步我们要生成微信jssdk的config：
```java
// 实例化配置信息
           JSSDKConfigurator jssdk = new JSSDKConfigurator(
				weixinProxy.getTicketHolder(TicketType.jsapi));
//需要配置的API集合
		jssdk.apis(JSSDKAPI.getLocation);
//得到配置的json字符串
String config = jssdk.toJSONConfig(getFullLoction()) 
//放到request作用域
		request.setAttribute("jssdk", config);
```
其中构造函数的ticket保存类可调用WeixinProxy#getTicketHolder获取
getFullLoction函数获取的是当前网页的URL，不包含#及其后面部分
可以参考：
```java
protected String getRootLocation() {
		int port = request.getServerPort();
		if (port == 80) {
			return String.format("%s://%s", request.getScheme(),
					request.getServerName());
		} else {
			return String.format("%s://%s:%s", request.getScheme(),
					request.getServerName(), port);
		}
	}

	protected String getFullLoction() {
		String root = getRootLocation();
		String queryString = request.getQueryString();
		return String.format("%s%s%s", root, request.getRequestURI(),
				StringUtil.isNotBlank(queryString) ? "?" + queryString : "");
	}
```

第二步在页面上使用：
```javascript
<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script type="text/javascript">
	wx.config(${jssdk});
	$('button').on('click',function(e){
		wx.getLocation({
		    type: 'wgs84', // 默认为wgs84的gps坐标，如果要返回直接给openLocation用的火星坐标，可传入'gcj02'
		    success: function (res) {
		        var latitude = res.latitude; // 纬度，浮点数，范围为90 ~ -90
		        var longitude = res.longitude; // 经度，浮点数，范围为180 ~ -180。
		        var speed = res.speed; // 速度，以米/每秒计
		        var accuracy = res.accuracy; // 位置精度
		    }
		});
	});
</script>
```

感谢使用。

**Comment by ygp1026** [comment]
谢谢楼主，十分详细。页面已经可以应用

咨询一下另外一个获取地理位置的接口，是“获取用户地理位置：用户同意上报地理位置后，每次进入公众号会话时，都会在进入时上报地理位置”

<xml>
<ToUserName><![CDATA[toUser]]></ToUserName>
<FromUserName><![CDATA[fromUser]]></FromUserName>
<CreateTime>123456789</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[LOCATION]]></Event>
<Latitude>23.137466</Latitude>
<Longitude>113.352425</Longitude>
<Precision>119.385040</Precision>
</xml>


这个接口我们可以根据需要进行调用吗？  
因为我是在后台有些步骤需要使用获取到对应的坐标，如果再到前台可能就比较麻烦了。
是不是要用Java模拟调用javascript进行执行相关的方法？

**Comment by foxinmy** [comment]
是这样的。
在微信里面有个被动回调的模式，即用户主动发消息给公众号然后公众号再回调我们的服务器：

用户发消息->微信服务器->我们的服务器(在开发者配置中填写的服务器URL地址)

你上面说的 “获取用户地理位置：用户同意上报地理位置后，每次进入公众号会话时，都会在进入时上报地理位置” 属于被动回调中的[上报地理位置事件消息](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140454&token=&lang=zh_CN)。

在weixin4j里面使用[server](https://github.com/foxinmy/weixin4j/tree/master/weixin4j-server)包去做处理，具体用法见：https://github.com/foxinmy/weixin4j/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Server

根据你的业务应该是用户每次上报时都需要将坐标信息保存下来(持久化等)，伪代码：
```java
public class LocationMessageHandler extends
		MessageHandlerAdapter<LocationEventMessage> {
	@Override
	public WeixinResponse doHandle0(WeixinRequest request,
			LocationEventMessage message) throws WeixinException {
		// message.getLatitude(); // 地理位置纬度
               // message.getLongitude();//地理位置精度
               // 持久化或者其它存储操作
            // 返回一个空白成功回复
		return BlankResponse.global;
	}
}
```

**Comment by ygp1026** [comment]
谢谢楼主，我这边最终决定使用这2个模式结合的情况来使用。
1、用户登录后使用默认的（上一次上报的）
2、如果没有获取到再页面单独定位
