### ISSUE TITLE
独立出来  netty服务器&消息分发  是基于什么考虑

### ISSUE THREAD

**Issue by opendever** [foxinmy/weixin4j#61]
有什么特殊的优势么？
目前其他开源sdk都没有这么做的，
感觉独立出来使用不是很方便，很多业务逻辑要重复的弄两份。
墙裂建议提供lib版本。

**Comment by foxinmy** [comment]
感谢关注。
我的想法是这样的：
在微信开放中有两个模式，被动模式跟主动模式，weixin4j分别做了实现。
主动模式就是weixin4j-mp这种SDK包了，被动模式就是server包，可以单独作为一个独立服务启动。
server包实现原理跟其它开源sdk不一样，它`不依赖于任何web容器`，内部构建了一个消息服务器。
明显的优势没有，甚至对现有系统的集成更加麻烦，如果现有系统不是rpc架构的话可能业务逻辑确实重复弄两份。
其实server包比较适用于单独服务发布，业务处理通过rpc的方式去调用，这样的场景。
如果不是这样的话，那么就需要跟现有的系统去做集成：
 + 依赖weixin4j-server包
 + 定义处理消息的Handler
 + 启动消息服务(这里值得注意的是最好使用一个单独线程去启动服务)：参考[example项目](https://github.com/foxinmy/weixin4j/tree/master/weixin4j-example)

**Comment by opendever** [comment]
大型项目或许有需要，对于小型项目，不想搞太复杂啊，这样分离出来至少要起两个监听（多一个服务维护成本）。还是建议能独立出来一个 :smile:

**Comment by foxinmy** [comment]
重复 #49
