### ISSUE TITLE
maven仓库中能查到weixin4j-server的最高版本只有1.1.7

### ISSUE THREAD

**Issue by qi04072008** [foxinmy/weixin4j#63]
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.foxinmy%22%20AND%20a%3A%22weixin4j-server%22

**Comment by foxinmy** [comment]
嗯，目前最高版本就是1.1.7。weixin4j-server跟mp、qy的版本号是不同步的，是有遇到什么问题吗？发自网易邮箱大师
            在2016年05月14日 17:48，qi04072008 写道:http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.foxinmy%22%20AND%20a%3A%22weixin4j-server%22

**Comment by qi04072008** [comment]
那没问题了，thanks
