### ISSUE TITLE
getMenuSetting()方法出现空指针

### ISSUE THREAD

**Issue by cywcy** [foxinmy/weixin4j#65]
通过微信平台收到菜单列表，出现空指针的是ArticleExtraProcessor中processExtra方法的Object，debug时候它确实一直都是null。数据如下（部分汉字已替换删除）：{"is_menu_open":1,"selfmenu_info":{"button":[{"name":"关于","sub_button":{"list":[{"type":"news","name":"简介","value":"_vei6v2EFzzuGgUCFaUeI0KuEWuyAGFhiXdbwvzAlQg","news_info":{"list":[{"title":"简介","author":"CYX","digest":"您好，欢迎您进入微信平台！","show_cover":0,"cover_url":"http:\/\/mmbiz.qpic.cn\/mmbiz\/vd1jo3MLiaahTqicY062mFP4GkARanJZib2Uibpz9nIicuyOMwMMG7qOeVV5e3HnHNY6GLPgjRPKZia3HI01cFyOGRQQ\/0?wx_fmt=jpeg","content_url":"http:\/\/mp.weixin.qq.com\/s?__biz=MzI4MDE0NTExNQ==&mid=412318764&idx=1&sn=f083748558b95da261e4297d350a0395#rd","source_url":""}]}},{"type":"news","name":"联系方式","value":"t7e20wipDxxmsoxOnBiHLX9QD20Dmm5XHrsAybjjVJw","news_info":{"list":[{"title":"联系方式","author":"CYX","digest":"sadfsfdsfdsfdsaf：","show_cover":1,"cover_url":"http:\/\/mmbiz.qpic.cn\/mmbiz\/vd1jo3MLiaahJQSc9GCmhcXicXppRw70MA1etavpfrrp1tngHWp05YmI5I1wtNEcKLMAOpfCG7Dqib812xNY3CtJg\/0?wx_fmt=jpeg","content_url":"http:\/\/mp.weixin.qq.com\/s?__biz=MzI4MDE0NTExNQ==&mid=412328264&idx=1&sn=9108966d31e77eb7ea10e5fa84e72680#rd","source_url":""}]}},{"type":"text","name":"特色","value":"全免"},{"type":"img","name":"我","value":"cF8xsUMQpOyqSXlnzvNkbrg4uTdpnz9Op8Y-XB1M6l98eH4jHsxrDase92Q-7dmf"}]}},{"name":"业务介绍","sub_button":{"list":[{"type":"news","name":"业务","value":"t7e20wipDxxmsoxOnBiHLbXK-ZBIwrEquY6hOscYx-Y","news_info":{"list":[{"title":"w业务","author":"CYX","digest":"一:服务简介","show_cover":0,"cover_url":"http:\/\/mmbiz.qpic.cn\/mmbiz\/vd1jo3MLiaahJQSc9GCmhcXicXppRw70MAwL8DdbGaAHGfLYuMzFAOTU5bKGVKNgyY0xoNuoQ9UzicUdsIpKbMs4w\/0?wx_fmt=jpeg","content_url":"http:\/\/mp.weixin.qq.com\/s?__biz=MzI4MDE0NTExNQ==&mid=412322071&idx=1&sn=946f4c6252ceea8e635b657a0083fd3d#rd","source_url":""},{"title":"rrr","author":"","digest":".rtddf","show_cover":0,"cover_url":"http:\/\/mmbiz.qpic.cn\/mmbiz\/vd1jo3MLiaahJQSc9GCmhcXicXppRw70MAEIR0OBPmnFGHnNIH8icr6L2ia6sXjickakLSWibsO1WcWmVxicEmmcEziaRA\/0?wx_fmt=jpeg","content_url":"http:\/\/mp.weixin.qq.com\/s?__biz=MzI4MDE0NTExNQ==&mid=412322071&idx=2&sn=fc3f84f48b7b4c063f06ca769fbbc0cf#rd","source_url":""},{"title":"dfsa","author":"CYX","digest":"产品描述","show_cover":0,"cover_url":"http:\/\/mmbiz.qpic.cn\/mmbiz\/vd1jo3MLiaahJQSc9GCmhcXicXppRw70MAaPca4nMRaedYGibIu093icO5Cica0mt2pjI7CDLgtV064qSHNCBm93qEQ\/0?wx_fmt=jpeg","content_url":"http:\/\/mp.weixin.qq.com\/s?__biz=MzI4MDE0NTExNQ==&mid=412322071&idx=3&sn=011f8627a51c53183a76564c85cf13cb#rd","source_url":""}]}},{"type":"news","name":"fdgdfg务","value":"t7e20wipDxxmsoxOnBiHLXPWTYimx8qbdO_gG0b-3aE","news_info":{"list":[{"title":"对公存款","author":"CYX","digest":"细则","show_cover":0,"cover_url":"http:\/\/mmbiz.qpic.cn\/mmbiz\/vd1jo3MLiaahJQSc9GCmhcXicXppRw70MA04nwu6Lqt7Upyv5NjmCzy5cQ4KG0ICeIgJPw1xv1o0iaoY7qEE8LhNw\/0?wx_fmt=jpeg","content_url":"http:\/\/mp.weixin.qq.com\/s?__biz=MzI4MDE0NTExNQ==&mid=412326286&idx=1&sn=2a5c0d915dd181255b87371b506a71a4#rd","source_url":""}]}},{"type":"news","name":"sdfds业务","value":"t7e20wipDxxmsoxOnBiHLVh2RpHZDAqz5VbEiYSUnKA","news_info":{"list":[{"title":"sdfds业务","author":"CYX","digest":"细则","show_cover":1,"cover_url":"http:\/\/mmbiz.qpic.cn\/mmbiz\/vd1jo3MLiaahJQSc9GCmhcXicXppRw70MA3HgvASiboyV9kh91fGZy0l0AJk5JVppzt2kBZHf3KKzdfQSgD7zzrMg\/0?wx_fmt=jpeg","content_url":"http:\/\/mp.weixin.qq.com\/s?__biz=MzI4MDE0NTExNQ==&mid=412323286&idx=1&sn=6e90cfb2cefa119c971ae80355550e51#rd","source_url":""}]}}]}},{"name":"最新活动","sub_button":{"list":[{"type":"view","name":"\"节节\"","url":"http:\/\/www.rabbitpre.com\/m\/JZfUZZJ3g?sui=c9B8iM85&lc=1&from=singlemessage&isappinstalled=0#from=share"}]}}]}}

**Comment by foxinmy** [comment]
感谢反馈。
确认为bug，已修复，请关注最新代码。

**Comment by cywcy** [comment]
客气，我还得感谢您呢！给大家提供了这么方便的工具！

2016-05-24 

wangchuangye45 



发件人：jinyu <notifications@github.com>
发送时间：2016-05-24 10:23
主题：Re: [foxinmy/weixin4j] getMenuSetting()方法出现空指针 (#65)
收件人："foxinmy/weixin4j"<weixin4j@noreply.github.com>
抄送："cywcy"<wangchuangye45@126.com>,"Author"<author@noreply.github.com>

感谢反馈。
确认为bug，已修复，请关注最新代码。
