### ISSUE TITLE
WeixinPayProxy.createMICROPayRequest 提交被扫支付失败

### ISSUE THREAD

**Issue by zhenghaixiang** [foxinmy/weixin4j#66]
博主,麻烦看下哦!
1.调用weixinPayProxy.createMICROPayRequest()出现异常.
<return_msg><![CDATA[trade_type参数格式错误]]></return_msg>
2.调用的接口有问题:weixin request >> POST https://api.mch.weixin.qq.com/pay/unifiedorder
3.PayApi.createPayRequest 这里出现错误.刷卡支付应该不用先调用统一下单接口吧?

**Comment by foxinmy** [comment]
感谢反馈。
请问使用的版本号是多少？

**Comment by zhenghaixiang** [comment]
1.6.8

**Comment by foxinmy** [comment]
非常抱歉。。确认为bug，已做修复，请关注最新代码。

**Comment by foxinmy** [comment]
另外 被扫(刷卡)支付这块 由于资源有限所以没真正测试过，正好你试试这个接口。(:

**Comment by zhenghaixiang** [comment]
:-D 感谢博主的辛勤付出~

**Comment by zhenghaixiang** [comment]
com.foxinmy.weixin4j.exception.WeixinException: FAIL >> 缺少参数
博主,我看了下提交刷卡支付的参数MchPayPackage,这里少了些微信刷卡支付需要的参数噢!
1.mch_id,sub_mch_id,device_info

**Comment by foxinmy** [comment]
请问你咋调用的。
调用的参数是啥？
weixin4j.properties怎么填写的？

**Comment by zhenghaixiang** [comment]
WeixinPayProxy weixinPayProxy = new WeixinPayProxy();
weixinPayProxy.createMicroPayRequest("130989479010439013", "test", System.currentTimeMillis()+"", 0.01, "127.0.0.1", "ok");
1.我看了下,刷卡支付的参数没有像其他支付方式一样执行这个方法:MerchantResult.declareWeixinPayAccount(WeixinPayAccount weixinPayAccount)
2.应该是上次更改后出现的问题.

**Comment by foxinmy** [comment]
嗯 你再试试。weixin4j.properties记得配置好。

**Comment by zhenghaixiang** [comment]
博主，我测试微信支付遇到两个问题。
1.测试用例统一下单的nativePay方法，new MchPayPackage(...),构造方法没有把tradeType赋值
ps：我把tradeType赋值后，可以生成订单
2.测试用例的testMicroPay方法（已经赋值tradeType），微信返回无效的trade_type.
原因，刷卡支付的api不能传trade_type参数。我在PayApi第109行加了payPackage.setTradeType(null);才能发起交易成功

博主有空看下喔^_^
