### ISSUE TITLE
JSSDKAPI的使用

### ISSUE THREAD

**Issue by ygp1026** [foxinmy/weixin4j#68]
代码调试通了，Java代码里面可以获取到相关config配置，但是jsp页面总是无法正常分享，shareClick()已经执行到alert()111;
但是没有分享效果
我的代码部署到阿里云，域名已经备案，微信端JS安全域名也已经指定

又要麻烦楼主了。

--------------------spring controller里面的代码
`JSSDKConfigurator jssdk = new JSSDKConfigurator(
        mpweixinProxy.getTicketHolder(TicketType.jsapi));
        //需要配置的API集合
        jssdk.apis(JSSDKAPI.onMenuShareTimeline);
       //得到配置的json字符串
	String config = jssdk.toJSONConfig("http://www.XXXXX.cn/weixin/education/product/detail/1"); 
	//放到request作用域
	System.out.println(config);
	model.addAttribute("jssdk",config);`
------------------------------------config信息获取正常
`{"timestamp":"1464093282","appId":"3333333485a58c3e3d","jsApiList":["onMenuShareTimeline"],"nonceStr":"3333333pQAqPSIMXAD8OZksw","debug":false,"signature":"c543b6251a0d234fcd163bacb4594242b14fb1a0"}
`
--------------JSP页面
`<script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script type="text/javascript">	
	var jssdk = ${jssdk};
	wx.config(jssdk);
	function shareClick(){
                alert(111);
		wx.onMenuShareTimeline({
    	    title: '-${record.name}', // 分享标题
    	    link: '<%=request.getContextPath() %>/weixin/education/product/detail/${record.id}', // 分享链接
    	    imgUrl: '${imageRootPath}${institution.imagesOld}', // 分享图标
    	    success: function () {
    	    	alert("已经分享");
    	        //用户确认分享后执行的回调函数
    	    },
    	    cancel: function () { 
    	        //用户取消分享后执行的回调函数
    	    	alert("分享取消");
    	    }
    	});
	}
</script>`

-----------触发事件
 `<div class="sub1" onclick="javascript:share()">
            	<button id="sharebt" onclick="shareClick()">测试分享</button>
            	<i id="wxshare" class="fa fa-share"></i>
 </div>`

------------参考您case写的
`https://github.com/foxinmy/weixin4j/issues/57`

**Comment by foxinmy** [comment]
感谢反馈。
代码并没有错，唯一不对的地方是你把微信的分享功能理解错了。

微信所谓的分享功能 <font color="#A52A2A" size="20">只能监听用户的分享动作，不能控制用户的分享行为。</font>

wx.onMenuShareTimeline 这段代码不是写在按钮的click事件里 而是在页面加载完毕后执行。

而 上述代码执行成功后，用户主动点击右上角的「...」按钮弹出操作界面。

再点击分享到朋友圈 这个时候成功后 才会触发  `success` 事件。

同理如果用户放弃分享则 触发 ·cancel· 事件。

这个分享功能比较坑了，我当初也被误导了。

**Comment by ygp1026** [comment]
刚刚把debug=true，确实看到了返回的信息{“errMsg”:"config:ok"}
我真的把分享功能理解错了 。呵呵

谢谢楼主指点了

**Comment by ygp1026** [comment]
已经完全理解这个接口：
如果执行有问题，debug=true的时候会弹出提示，例如提示签名错误
如果执行没用问题，则提示config:ok

-----如果执行有问题，则不会显示分享到朋友圈或者什么的，如果执行没用问题则会显示分享到XXXXXX
这个方法是分享之后调用使用的

感谢楼主普及，关闭改case
