### ISSUE TITLE
base微信支付请教

### ISSUE THREAD

**Issue by ygp1026** [foxinmy/weixin4j#69]
楼主https://github.com/foxinmy/weixin4j/wiki/%E6%94%AF%E4%BB%98%E7%A4%BA%E4%BE%8B(PayHandler)
这个链接中您给了一个支付的例子，这个例子中第一步生成的json是要传递到JSP页面中去还是？

我用了最新的1.6.9写了一段，发现这个里面一致都是一个对象，不能直接生成json了？

现在支付的例子有从前到后一起的吗？
我根据你那个链接写的一个例子
`@RequestMapping({"/weixin/pay/{orderId}/"})
	public JSONObject jsPay(HttpSession httpSession,@PathVariable long orderId,@RequestParam(value="productDes") String productDes,Model model) throws WeixinException{
		String openid = (String) httpSession.getAttribute("openid");
		
		WeixinPayAccount weixinAccount = JSON.parseObject(Weixin4jConfigUtil.getValue("account"),WeixinPayAccount.class);
		JSONObject obj = new JSONObject();
		//String openId, String body, String outTradeNo, double totalFee,String notifyUrl, String createIp, String attach
		MchPayRequest payRequest = weixinPayProxy.createJSPayRequest(openid, productDes , orderId+"", 0.10,"支付回调URL", "139.196.207.94","");
		_obj.put("jsapi", payRequest.asPayJsRequestJson());_这个方法好像没有了
		// 保存 prepayid 便于重复发起支付
		//String prepayId = payRequest.getPrePayId();
		//payRequest = new MchPayRequest(weixinAccount.getId(), prepayId);
		//obj.put("jsapi", payRequest.asPayJsRequestJson());
		return obj;
	}`

**Comment by ygp1026** [comment]
对于支付方面还是小白

**Comment by foxinmy** [comment]
感谢反馈。
请关注最新的[JS支付示例](https://github.com/foxinmy/weixin4j/wiki/%E6%94%AF%E4%BB%98%E7%A4%BA%E4%BE%8B(JSAPI))

**Comment by ygp1026** [comment]
经过了半天的摸索和学习终于集成成功了
十分感谢楼主。
从一开始学习微信开发就是跟着你这个项目在走，当时很奇怪楼主为什么没有例子，不过看楼主在线回复和在线支持真的很给力。基本上楼主1天内解决掉我的咨询。
1、微信的主动调用接口
2、微信的被动调用和web集成
3、outh2集成
4、地理位置获取
5、微信分享
6、微信支付

这一路下来，基本上对微信开发、对楼主的封装代码已经很了解了。十分感谢楼主
