### ISSUE TITLE
您好，开发这个库是主要是做什么，有实际产品在用吗

### ISSUE THREAD

**Issue by zhfnjust** [foxinmy/weixin4j#7]

**Comment by foxinmy** [comment]
起初的想法是做给自己公司用的，后来「自作主张」抽取出来形成独立的项目，用来方便有需要的朋友。

weixin4j-mp和weixin4j-qy分别是公众平台跟企业号的API调用工具包，weixin4j-server想做成针对微信消息的响应服务器，目前还在实现中。

多谢关注！

**Comment by zhfnjust** [comment]
你好，你是环信的工程师吗

**Comment by foxinmy** [comment]
可能是「easemob4j」项目引起误会了,事实上也是为公司某个项目而写的.

**Comment by zhfnjust** [comment]
这个项目怎么部署调试啊

**Comment by zhfnjust** [comment]
微信只能 用80端口，你里面配置的的是8080，怎么调试的啊

**Comment by foxinmy** [comment]
1.目前的server工程我正在重构中,代码已经改动不少

2.可以看以前的server实现,分支地址:https://github.com/foxinmy/weixin4j/tree/1.3netty/

3.端口问题可以将netty.properties中的port属性值改成80,`或者用nginx做转发`
