### ISSUE TITLE
建议先实现微信的各种接口。cache的优化，建议放到最后。

### ISSUE THREAD

**Issue by 907043175** [foxinmy/weixin4j#70]

**Comment by foxinmy** [comment]
嗯。谢谢你的建议。
cache这块在这个版本重构后，不会再有很大的改动了。
对于迟迟还未实现的接口有一部原因是没有相关的资源：比如「公众号第三方服务应用」接口是需要有开放平台的开发者才能更好去调试接口实现。

感谢关注。（：
