### ISSUE TITLE
消息处理一定要使用weixin4j-server吗？

### ISSUE THREAD

**Issue by tangweixin** [foxinmy/weixin4j#71]
# 消息处理一定要使用weixin4j-server吗？
### 有没有办法，可以直接使用springMVC来接受请求，并进行消息的转发呢？

**Comment by foxinmy** [comment]
嗯，目前是这样的。不过我正在实现一个servlet的支持。发自网易邮箱大师
            在2016年06月04日 19:42，thomastangweixin 写道:消息处理一定要使用weixin4j-server吗？

消息处理这种方式很不错的，但是，一定要使用weixin4j-server，自己另外启动一个监听服务吗？

有没有办法，可以直接使用springMVC来接受请求，并进行消息的转发呢？

**Comment by tangweixin** [comment]
好滴，希望能早些开发出来，毕竟使用现成的servlet来处理请求比较方便。

**Comment by foxinmy** [comment]
#49
