### ISSUE TITLE
weixin-server中如何才能让同一corpid支持多个应用

### ISSUE THREAD

**Issue by eonezhang** [foxinmy/weixin4j#72]
使用wexin-server的时候，在微信企业号后台通过指定url(如?weixin_id=wx3bb84caaa9d73b58&encrypt_type=AES)可以为企业号的某个应用启用回调模式，如果要为企业号的多个应用启用回调，现在可以做到吗?还是需要自己修改代码，增加参数来解决，比如增加一个agentId=应用ID

**Comment by foxinmy** [comment]
感谢使用。
weixin4j-server是支持多个应用的。每个应用的URL配置成一样的(weixin_id=wx3bb84caaa9d73b58&encrypt_type=AES)就好了。
这样的话企业号所有的应用下的用户消息都会被转发到url上来。
如果想要单独对某个应用做区分处理，这里有两个建议：
1、可以在handler里面做个判断。
2、可以针对不同应用起多个server服务，然后配置不同的url，比如：http://{agentId}.xxx.xx/weixin/server?weixin_id=wx3bb84caaa9d73b58&encrypt_type=AES

以上。

**Comment by eonezhang** [comment]
感谢回复，如果有机会，希望能为此项目贡献代码
