### ISSUE TITLE
server中MenuApi中createMenu0 菜单事件类型和官方API不完全一致

### ISSUE THREAD

**Issue by cywcy** [foxinmy/weixin4j#74]
createMenu0 中对ButtonType的判断，首先view本身是官方的标准类型，为啥要改为URL呢；其次只支持图文素材吗，其他的都标记为key发给官方了？ 
还有点建议，ButtonType.media_id和ButtonType.view_limited 不要合并为media_id，既然官方分为两个类型，作为工具包，理应保持一致；另外就是button类中ButtonType属性能否改为string，要不，在new button时候 要把string转为ButtonType，发送给微信时候又要把ButtonType转为string，有点多此一举，仅仅是为了保证开发者不出错的话，感觉有点不值当。

**Comment by foxinmy** [comment]
感谢关注。
>首先view本身是官方的标准类型，为啥要改为URL呢；

微信对于view类型的按钮所接收的参数格式是这样的：

> {
                   "type":"view",
                   "name":"搜索",
                   "url":"http://www.soso.com/"
               }

而在weixin4j的Butto类中只有一个content，它包含了所有的按钮类型的值，比如如果buttonType是view的话，那么这个content就相当于url，如果buttonType是click，那么这个content就是key。在调用接口传递给微信的时候就需要转换下这个content的name，所以才有了：
```java
if (object instanceof Button && name.equals("content")) {
							ButtonType buttonType = ((Button) object).getType();
							if (buttonType != null) {
								if (ButtonType.view == buttonType) {
									return "url";
								} else if (ButtonType.media_id == buttonType
										|| ButtonType.view_limited == buttonType) {
									return "media_id";
								} else {
									return "key";
								}
							}
						}
```

>其次只支持图文素材吗

不是，在微信的菜单有两种方式创建，第一是通过[公众平台](https://mp.weixin.qq.com)设置，这里方式可以创建图文菜单。另外一种方式是通过[API调用方式](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141013&token=&lang=zh_CN)创建。之所以在Buton中写了个`List<MpArticle> articles`是对前一种方式创建菜单的获取(见：com.foxinmy.weixin4j.mp.api.HelperApi.getMenuSetting() )，不过在Button中放一个这样的属性，确实容易引起误会，我会考虑优化的。

>其他的都标记为key发给官方了

见1.

>ButtonType.media_id和ButtonType.view_limited 不要合并为media_id，既然官方分为两个类型，作为工具包，理应保持一致；

这里的media_id指的是发送的JSON数据包都是media_id，而对调用者来说只需要关心content的值就好了。

>在new button时候 要把string转为ButtonType，发送给微信时候又要把ButtonType转为string

这里我坚持自己的想法。new Button的时候往往都是明确清晰的，应当是直接传入的枚举类型。而发送微信时是fastjson包做的转换，我认为并没有什么大碍。

以上。

再次感谢反馈。

**Comment by cywcy** [comment]
多些解疑！灰常感谢！

2016-06-11 

wangchuangye45 



发件人：jinyu <notifications@github.com>
发送时间：2016-06-11 11:02
主题：Re: [foxinmy/weixin4j] server中MenuApi中createMenu0 菜单事件类型和官方API不完全一致 (#74)
收件人："foxinmy/weixin4j"<weixin4j@noreply.github.com>
抄送："cywcy"<wangchuangye45@126.com>,"Author"<author@noreply.github.com>

感谢关注。
首先view本身是官方的标准类型，为啥要改为URL呢；
微信对于view类型的按钮所接收的参数格式是这样的：
{
"type":"view",
"name":"搜索",
"url":"http://www.soso.com/"
}
而在weixin4j的Butto类中只有一个content，它包含了所有的按钮类型的值，比如如果buttonType是view的话，那么这个content就相当于url，如果buttonType是click，那么这个content就是key。在调用接口传递给微信的时候就需要转换下这个content的name，所以才有了：
if (object instanceof Button && name.equals("content")) {
                            ButtonType buttonType = ((Button) object).getType();
                            if (buttonType != null) {
                                if (ButtonType.view == buttonType) {
                                    return "url";
                                } else if (ButtonType.media_id == buttonType
                                        || ButtonType.view_limited == buttonType) {
                                    return "media_id";
                                } else {
                                    return "key";
                                }
                            }
                        }
其次只支持图文素材吗
不是，在微信的菜单有两种方式创建，第一是通过公众平台设置，这里方式可以创建图文菜单。另外一种方式是通过API调用方式创建。之所以在Buton中写了个List<MpArticle> articles是对前一种方式创建菜单的获取(见：com.foxinmy.weixin4j.mp.api.HelperApi.getMenuSetting() )，不过在Button中放一个这样的属性，确实容易引起误会，我会考虑优化的。
其他的都标记为key发给官方了
见1.
ButtonType.media_id和ButtonType.view_limited 不要合并为media_id，既然官方分为两个类型，作为工具包，理应保持一致；
这里的media_id指的是发送的JSON数据包都是media_id，而对调用者来说只需要关心content的值就好了。
在new button时候 要把string转为ButtonType，发送给微信时候又要把ButtonType转为string
这里我坚持自己的想法。new Button的时候往往都是明确清晰的，应当是直接传入的枚举类型。而发送微信时是fastjson包做的转换，我认为并没有什么大碍。
以上。
再次感谢反馈。
