### ISSUE TITLE
MediaApi中listMaterialMedia方法获取不到素材

### ISSUE THREAD

**Issue by cywcy** [foxinmy/weixin4j#75]
经查询，微信平台已返回素材，但MediaRecord类中的items并不能得到赋值，微信平台返回的是多个并列的item，并没有items标签

**Comment by foxinmy** [comment]
感谢反馈。

确认为bug，已作修复，请关注最新代码。

**Comment by cywcy** [comment]
收到，辛苦了。发现个问题。刚提交的代码中，接口CardCoupon引用的类找不到
[ERROR] /F:/workspace/eclipse/weixin4j/weixin4j-mp/src/main/java/com/foxinmy/weixin4j/mp/card/CardCoupon.java:[27,16] 找不到符号
[ERROR] 符号:   类 CouponBaseInfo
[ERROR] 位置: 接口 com.foxinmy.weixin4j.mp.card.CardCoupon
[ERROR] /F:/workspace/eclipse/weixin4j/weixin4j-mp/src/main/java/com/foxinmy/weixin4j/mp/card/CardCoupon.java:[34,16] 找不到符号
[ERROR] 符号:   类 CouponAdvancedInfo
[ERROR] 位置: 接口 com.foxinmy.weixin4j.mp.card.CardCoupon
[ERROR] /F:/workspace/eclipse/weixin4j/weixin4j-mp/src/main/java/com/foxinmy/weixin4j/mp/card/CardCoupon.java:[41,16] 找不到符号
[ERROR] 符号:   类 CouponDetailInfo
[ERROR] 位置: 接口 com.foxinmy.weixin4j.mp.card.CardCoupon

另外。example工程中 少个SpringBeanFactory类
2016-06-11 

wangchuangye45 



发件人：jinyu <notifications@github.com>
发送时间：2016-06-11 11:31
主题：Re: [foxinmy/weixin4j] MediaApi中listMaterialMedia方法获取不到素材 (#75)
收件人："foxinmy/weixin4j"<weixin4j@noreply.github.com>
抄送："cywcy"<wangchuangye45@126.com>,"Author"<author@noreply.github.com>

感谢反馈。
确认为bug，已作修复，请关注最新代码。

**Comment by cywcy** [comment]
我看你刚提交的没有这几个类，问题依然存在
[ERROR] /F:/workspace/eclipse/weixin4j/weixin4j-mp/src/main/java/com/foxinmy/weixin4j/mp/card/CardCoupon.java:[27,16] 找不到符号
[ERROR] 符号:   类 CouponBaseInfo
[ERROR] 位置: 接口 com.foxinmy.weixin4j.mp.card.CardCoupon
[ERROR] /F:/workspace/eclipse/weixin4j/weixin4j-mp/src/main/java/com/foxinmy/weixin4j/mp/card/CardCoupon.java:[34,16] 找不到符号
[ERROR] 符号:   类 CouponAdvancedInfo
[ERROR] 位置: 接口 com.foxinmy.weixin4j.mp.card.CardCoupon
[ERROR] /F:/workspace/eclipse/weixin4j/weixin4j-mp/src/main/java/com/foxinmy/weixin4j/mp/card/CardCoupon.java:[41,16] 找不到符号
[ERROR] 符号:   类 CouponDetailInfo
[ERROR] 位置: 接口 com.foxinmy.weixin4j.mp.card.CardCoupon

2016-06-11 

wangchuangye45 



发件人：jinyu <notifications@github.com>
发送时间：2016-06-11 12:01
主题：Re: [foxinmy/weixin4j] MediaApi中listMaterialMedia方法获取不到素材 (#75)
收件人："foxinmy/weixin4j"<weixin4j@noreply.github.com>
抄送："cywcy"<wangchuangye45@126.com>,"Author"<author@noreply.github.com>

提交有误，请再更新。。。

**Comment by cywcy** [comment]
不好意思，提交上了，我这边问题多谢！

2016-06-11 

wangchuangye45 



发件人：jinyu <notifications@github.com>
发送时间：2016-06-11 12:01
主题：Re: [foxinmy/weixin4j] MediaApi中listMaterialMedia方法获取不到素材 (#75)
收件人："foxinmy/weixin4j"<weixin4j@noreply.github.com>
抄送："cywcy"<wangchuangye45@126.com>,"Author"<author@noreply.github.com>

提交有误，请再更新。。。

**Comment by foxinmy** [comment]
SpringBeanFactory 类是可选的，是针对weixin4j-server项目，如果项目中有用到spring的话，就采用spring去获取bean，否则就通过class.newInstance的方式去实例化。

```xml
<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>4.2.1.RELEASE</version>
		</dependency>
```

**Comment by cywcy** [comment]
你好，今天遇到一个问题，我写了个handler，源码如下。现在遇到的问题是，我有个菜单正常效果是点击菜单后，直接打开一个网页。而且我这边的handler也收到了这个事件推送，但我该如何回复WeixinResponse呢，我用TextResponse回复的话，微信窗口直接显示一个超链接，需要用户再点击下才能打开网页。
@Component
public class MenuEventMessageHandler extends MessageHandlerAdapter<MenuEventMessage> {

 @Override
 public WeixinResponse doHandle0(WeixinRequest request, MenuEventMessage message) throws WeixinException {
  String type = message.getEventType().toLowerCase();
  if(type.equals(ButtonType.click.name())){
   return new TextResponse(message.getEventKey());
  }else if(type.equals(ButtonType.view.name())){
   return new TextResponse(message.getEventKey());
  }else{
   return new SingleResponse("success");
  }
 }
}


2016-06-11 

wangchuangye45 



发件人：jinyu <notifications@github.com>
发送时间：2016-06-11 12:08
主题：Re: [foxinmy/weixin4j] MediaApi中listMaterialMedia方法获取不到素材 (#75)
收件人："foxinmy/weixin4j"<weixin4j@noreply.github.com>
抄送："cywcy"<wangchuangye45@126.com>,"Author"<author@noreply.github.com>

SpringBeanFactory 类是可选的，是针对weixin4j-server项目，如果项目中有用到spring的话，就采用spring去获取bean，否则就通过class.newInstance的方式去实例化。
<dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>4.2.1.RELEASE</version>
        </dependency>

**Comment by foxinmy** [comment]
如果想让用户点击按钮直接跳转的话：使用ButtonType.view创建就好了。
view类型的按钮就算服务器回复了消息微信也不会做任何处理的。
对于click类型只能通过用户点击消息(带超链接的文本、图文)上的链接才能进行跳转。
