### ISSUE TITLE
com.foxinmy.weixin4j.qy.api.NotifyApi split参数

### ISSUE THREAD

**Issue by wwlleo0730** [foxinmy/weixin4j#76]
微信返回使用‘|’作为分隔符，‘|’在正则内为特殊字符,需要转义。

该类第98,103,111行均有

if (obj.containsKey("invaliduser")) {
	idParameter.setUserIds(Arrays.asList(obj.getString("invalidlist")
		.split(IdParameter.SEPARATORS)));
}

//////////////////////////////////////////////////////////
String p = "str1|str2|str3";
System.out.println(p.split("\\\\|").length);

tagApi里也有。

**Comment by foxinmy** [comment]
十分抱歉。已修复，请关注最新代码。

**Comment by wwlleo0730** [comment]
同一个类 ，json解析写错了，报null错误

obj.getString("invalidlist")

if (obj.containsKey("invaliduser")) {
			idParameter.setUserIds(Arrays.asList(obj.getString("invalidlist")
					.split(IdParameter.SEPARATORS)));
}
