### ISSUE TITLE
刷卡支付时trade_type不需要传

### ISSUE THREAD

**Issue by xz1367** [foxinmy/weixin4j#78]
刷卡支付时trade_type不需要传入，否则会报trade_type类型错误，请改正之后重新发个jar包，谢谢！

**Comment by foxinmy** [comment]
感谢反馈。

这个刷卡支付接口 我确实没有真正测试过，由此带来的不便表示抱歉。

**Comment by foxinmy** [comment]
关于jar包其实我昨天才发的包到maven中央仓库，基本上是保持每隔一个月左右发布一个版本的频率。

所以可能需要你自己编译源码打包了。

感谢使用。
