### ISSUE TITLE
获取用户信息接口问题

### ISSUE THREAD

**Issue by ygp1026** [foxinmy/weixin4j#81]
楼主，我之前参考https://github.com/foxinmy/weixin4j/issues/64这个链接写了一个获取用户信息的方法
WeixinProxy 里面没有 OauthApi? #64 

最近我发现，如果已经关注过我的公众号，我的方法没问题，但是如果一个陌生的微信号访问我的公众号总是莫名其妙的报错，说我的token不是最新的，我打印了log，好像确实是不一致

===============日志
已经获取到code----031DwZ5k1R8kmz0bT96k1dyY5k1DwZ5W
GET https://api.weixin.qq.com/sns/oauth2/access_token?appid=xxxxxxxxxx&secret=xxxxxxxxxxxxxxxxxxxxxxxxx&grant_type=authorization_code
{"access_token":"17zCkz_5Iy3DJ7NfVKp1qLKD_1TRGd6b3RZEOisjf0aI365dZm5LI4a4IBIO2XmrCmSm7r0DbfTOxVdZCWmjw9jxkDteYgUiViOA8D19-d0","expires_in":7200,"refresh_token":"l4nKmX0cXQQw13H3gxUtCGpVaYjFcKhNgkY2aetP6RQjtEKyXn3QCeAOsmDWu1dGc5-I-sJJBxpuvrammN3QKww0OXBGH5Iajx3qEDKunUc","openid":"oROmat31fvmpl0oJg08TUDjtj7Z4","scope":"snsapi_userinfo"}

GET https://api.weixin.qq.com/cgi-bin/user/info?access_token=6AE-2scJJCJ5Swje7148CkrjQRoljt6-AlrGPrPqNb7aXyObR_48uDqvS2HDYYf7pTMMaKaDZ7acC1YsBWxgE-hMuV5hsfLBh3JcBPkuz_0V5eMxkyHx_IHTBSXX85EvPANdAGAHSF&openid=oROmat31fvmpl0oJg08TUDjtj7Z4&lang=zh_CN
{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest hint: [Vk0144vr22]"}
com.foxinmy.weixin4j.exception.WeixinException: 40001 >> invalid credential, access_token is invalid or not latest hint: [Vk0144vr22] >> 获取access_token时AppSecret错误，或者access_token无效

========我的代码
`
System.out.println("已经获取到code----"+code);

OauthToken oauthToken = oauthApi.getOauthToken(code);

System.out.println("---------新用户-----------自动注册用户");

User user = mpweixinProxy.getUser(oauthToken.getOpenId());
`

**Comment by foxinmy** [comment]
感谢反馈。

oauth里面的token跟调用接口时的token不太一样。

oauth授权有两种：base/userinfo。前者只能拿到用户的openid，而后者是可以拿到用户的基本信息，而且不管这个用户有没有关注当前的公众号，但是有个不好的地方是会弹出一个授权确认的页面，影响到用户的体验。

无论哪种方式对于 WeixinProxy.getUser(String openId);接口应该都没有影响。
对于userinfo授权可以调用`com.foxinmy.weixin4j.mp.api.OauthApi.getUser(OauthToken token)`接口。

但 这里报了一个 40001 错误 就值得关注了，请加群559850102讨论。

感谢使用。

**Comment by ygp1026** [comment]
搞定 感谢楼主
原因配置文件错误，配置后正确
`//User user = mpweixinProxy.getUser(oauthToken.getOpenId());
				User user = oauthApi.getUser(oauthToken);`
