### ISSUE TITLE
模板消息超过10000人获取用户id会无限循环

### ISSUE THREAD

**Issue by 296677863** [foxinmy/weixin4j#82]
for (;;) {
			f = getFollowing(nextOpenId);
			userList.addAll(f.getUserList());
			if (f.getCount() == f.getTotal() || f.getCount() == 0) {
				break;
			}

			nextOpenId = f.getNextOpenId();
		}

**Comment by 296677863** [comment]
f.getNextOpenId() 会返回空

**Comment by foxinmy** [comment]
感谢反馈。
确认为bug，已修复，请关注最新代码。

**Comment by 296677863** [comment]
忘记说这段代码会出现空指针异常f.getUserList();要么放到if下面，要么加个判断！

**Comment by foxinmy** [comment]
超过10000人时返回的内容是什么？

**Comment by 296677863** [comment]
当NextOpenId请求最后一个时再去请求时，返回的是NextOpenId是“”; f.getOpenIds() 也是null

**Comment by 296677863** [comment]
不会出现无限循环，昨天说错了。userList.addAll(f.getUserList());这段会出现null指针异常

**Comment by 296677863** [comment]
f = getFollowingOpenIds(nextOpenId);
			if (f.getCount() == 0) {
				break;
			}
			openIds.addAll(f.getOpenIds());
			nextOpenId = f.getNextOpenId();

**Comment by foxinmy** [comment]
恩 明白了

**Comment by 296677863** [comment]
加个QQ 296677863，以后有问题联系方便点，有没有什么群。

**Comment by foxinmy** [comment]
559850102 QQ群 :-)
