### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by sbb7060777** [foxinmy/weixin4j#83]
写的很好  但是文档还是过于简单    没有 使用的 demo  上手需要时间   一般用的时候 都是 项目开发 需要快速上手 希望以后完善文档  谢谢

**Comment by foxinmy** [comment]
嗯 感谢建议。非常好。

文档后续我会不断完善的。

**Comment by sbb7060777** [comment]
花了2个多小时  看懂了 楼主的 源码 。增长了知识。代码 封装 的很牛X。像你学习

**Comment by foxinmy** [comment]
:-) 大家一起交流学习。

**Comment by sbb7060777** [comment]
有一个问题  把weixin4j-server集成到spring中，开启一个线程启动微信netty服务。当微信发送消息给我的应用时(给微信的一个接口)  怎么把微信传来的消息  给 netty服务  让netty服务返回的   。  代码没看到在什么地方处理的   请大神指点

**Comment by foxinmy** [comment]
是这样的。

weixin4j-server其实更好的方式是单独作为服务启动，但是考虑到在现有的系统(spring-mvc等)上开发，所以不得不开启一个线程去启动服务，我是觉得这样做比较畸形，其实还是用的netty相关API，没有依赖servletAPI，或者说我还没有对servletAPI进行支持，但后续会考虑支持。

刚才说到weixin4j-server其实是一个服务，它会监听某个端口(默认是30000)，只需要保证填写的服务器URL能够转发到这上面来就行了，这里还有必要说下，微信服务器URL目前是不支持非80端口的，考虑到80端口的重要性，最好通过域名转发(nginx)的方式去做，不要直接用weixin4j-server监听80端口。

weixin4j-server的处理流程可以看看这个图：https://camo.githubusercontent.com/2be5790ba99a7e82f0c6b677889e677a1d5e6168/687474703a2f2f376d6a347a732e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f77656978696e346a2e706e67
开发者更多是写各种MessageHandler，至于代码层面可以关注下：`com.foxinmy.weixin4j.socket`包下的类和`com.foxinmy.weixin4j.dispatcher.WeixinMessageDispatcher`，这里我就不细说了。

**Comment by sbb7060777** [comment]
嗯。了解了。原来netty会监听端口获取到请求的参数。谢谢指点

**Comment by kingven** [comment]
你好，大神：
我使用了netty转发微信请求到30000端口，但是没有处理微信请求，也没有提示错误。
另外，如果微信请求的是一个jsp页面，如何通过netty响应请求？
谢谢！

**Comment by foxinmy** [comment]
@kingven
 
感谢关注。

正如上面所说，server只负责处理具体消息，没有具体页面。因为整个过程的交互是不涉及到页面的。

没有响应消息要看具体细节，可以加群交流下：559850102
