### ISSUE TITLE
请问一下关于app支付，返回给app端的参数值

### ISSUE THREAD

**Issue by caokang** [foxinmy/weixin4j#84]
请问一下关于app支付，返回给app端的参数值，是否有封装，还是说要自己来处理。感谢。

![qq 20160725162625](https://cloud.githubusercontent.com/assets/3904995/17094921/9b17b5c4-5284-11e6-9a15-d55edd43a6ca.png)

https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_12

**Comment by foxinmy** [comment]
app支付weixin4j有实现。见 WeixinPayProxy#createAppPayRequest

but，app支付没有实际测试过，请小心使用。

感谢反馈。

**Comment by caokang** [comment]
感谢回复。我目前使用的就是 WeixinPayProxy#createAppPayRequest，这个的作用是在服务器端生成预支付交易单，主要的返回值是，mchPayRequest.getPrePayId()，然后拿到这个值，再做接下来的app参数加密操作。但是现在app客户端还需要一个类似但是不一样的参数列表要传给微信的sdk使用，图如上面的所示。这块也涉及到，加密验证操作，虽然可以自己来处理，但感觉相同的功能还需要再实现一边。我看了一下源码，目前没有封装这个返回列表。想请问一下，可否把这个也封装到sdk里。

**Comment by foxinmy** [comment]
请关注：com.foxinmy.weixin4j.payment.mch.APPPayRequest#toRequestString

如有问题可加群交流：559850102

**Comment by caokang** [comment]
我刚看了这个，我说的就是这个。非常感谢。
