### ISSUE TITLE
AgentSetter类缺少某些字段的get方法

### ISSUE THREAD

**Issue by macthink** [foxinmy/weixin4j#87]
/**
	 * 是否接收用户变更通知。0：不接收；1：接收。主页型应用无需该参数
	 */
	@JSONField(name = "isreportuser")
	private boolean isReportUser;

	/**
	 * 是否上报用户进入应用事件。0：不接收；1：接收。主页型应用无需该参数
	 */
	@JSONField(name = "isreportenter")
	private boolean isReportEnter;

以上两个字段没有get方法只有set方法

**Comment by foxinmy** [comment]
真的太抱歉了。

一时疏忽犯了这样的低级错误。

感谢反馈，最新代码已加上。:-)

**Comment by macthink** [comment]
好的，谢谢。会在哪个版本推送到中央库？

**Comment by foxinmy** [comment]
实不相瞒，其实昨天我release了一个新版本到中央库。

所以....可能不会那么快，暂时建议你自己install或者deploy到私服吧，非常抱歉。

**Comment by macthink** [comment]
好的。
