### ISSUE TITLE
微信支付刷卡失败

### ISSUE THREAD

**Issue by zhenghaixiang** [foxinmy/weixin4j#94]
博主，我测试微信支付遇到两个问题。
1.测试用例统一下单的nativePay方法，new MchPayPackage(...),构造方法没有把tradeType赋值
ps：我把tradeType赋值后，可以生成订单
2.测试用例的testMicroPay方法（已经赋值tradeType），微信返回无效的trade_type.
原因，刷卡支付的api不能传trade_type参数。我在PayApi第109行加了payPackage.setTradeType(null);才能发起交易成功

博主有空看下喔^_^

**Comment by foxinmy** [comment]
嗯 感谢反馈。

这个nativePay支付的tradeType参数是有点问题的，最新代码我已做相应修改，可以关注下。

过几天会重新release到maven中央库。

**Comment by foxinmy** [comment]
1.7.5
