### ISSUE TITLE
weixin4j-server 如何接入微信？

### ISSUE THREAD

**Issue by Neo110** [foxinmy/weixin4j#99]
weixin4j-server 如何接入微信？

**Comment by foxinmy** [comment]
感谢关注。

首先可以看看：https://github.com/foxinmy/weixin4j/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Server


weixin4j-server  可以看成一个服务中间件，单独部署运行。

服务启动成功后会监听一个端口，对应微信设置的服务器URL地址。

**Comment by Neo110** [comment]
微信只支持 80 和 443 吧？

**Comment by Neo110** [comment]
这监听没什么可选性呀？为啥要做成独立的服务？

**Comment by foxinmy** [comment]
端口的问题可以通过代理子域名的方式解决。

我的想法是微信开发分成两大块：

1：主动模式，开发者主动调用微信接口（http）的方式，对应weixin4j-mp,weixin4j-qy的工具包封装了实现。

2：被动模式，微信服务器推送消息到公众号，开发者返回特定内容进行回复，也就是weixin4j-server的实现了。

以上。
